
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `pwr`=list(
        `type`="software", 
        `author`="Stephane Champely", 
        `year`=2020, 
        `title`="pwr: Basic Functions for Power Analysis", 
        `url`="https://CRAN.R-project.org/package=pwr"), 
    `pamlj`=list(
        `type`="software", 
        `author`="Marcello Gallucci", 
        `year`=2024, 
        `title`="pamlj: Power analysis in jamovi", 
        `url`="https://pamlj.github.io/"), 
    `jpower`=list(
        `type`="software", 
        `author`="Richard Morey, Ravi Selker", 
        `year`=2019, 
        `title`="jpower: A module to compute power for various designs within jamovi", 
        `url`="https://github.com/richarddmorey/jpower"))
