
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `pwr`=list(
        `type`="software", 
        `author`="Stephane Champely", 
        `year`=2020, 
        `title`="pwr: Basic Functions for Power Analysis", 
        `url`="https://CRAN.R-project.org/package=pwr"))
