
# This file is automatically generated, you probably don't want to edit this

datagenOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "datagenOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            dep_n = 50,
            covs = list(),
            factors = NULL,
            clusters = NULL,
            structure = NULL,
            clusters_comb = "cross",
            factors_comb = "cross", ...) {

            super$initialize(
                package="pamlj",
                name="datagen",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionString$new(
                "dep",
                dep)
            private$..dep_n <- jmvcore::OptionNumber$new(
                "dep_n",
                dep_n,
                default=50)
            private$..covs <- jmvcore::OptionArray$new(
                "covs",
                covs,
                default=list(),
                template=jmvcore::OptionString$new(
                    "covs",
                    NULL))
            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "opt1",
                            NULL))))
            private$..clusters <- jmvcore::OptionArray$new(
                "clusters",
                clusters,
                template=jmvcore::OptionGroup$new(
                    "clusters",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "opt1",
                            NULL))))
            private$..structure <- jmvcore::OptionArray$new(
                "structure",
                structure,
                template=jmvcore::OptionGroup$new(
                    "structure",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "variable",
                            NULL),
                        jmvcore::OptionString$new(
                            "cluster",
                            NULL))))
            private$..clusters_comb <- jmvcore::OptionList$new(
                "clusters_comb",
                clusters_comb,
                default="cross",
                options=list(
                    "cross",
                    "nested"))
            private$..factors_comb <- jmvcore::OptionList$new(
                "factors_comb",
                factors_comb,
                default="cross",
                options=list(
                    "cross",
                    "random"))
            private$..output <- jmvcore::OptionOutput$new(
                "output")

            self$.addOption(private$..dep)
            self$.addOption(private$..dep_n)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..clusters)
            self$.addOption(private$..structure)
            self$.addOption(private$..clusters_comb)
            self$.addOption(private$..factors_comb)
            self$.addOption(private$..output)
        }),
    active = list(
        dep = function() private$..dep$value,
        dep_n = function() private$..dep_n$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        clusters = function() private$..clusters$value,
        structure = function() private$..structure$value,
        clusters_comb = function() private$..clusters_comb$value,
        factors_comb = function() private$..factors_comb$value,
        output = function() private$..output$value),
    private = list(
        ..dep = NA,
        ..dep_n = NA,
        ..covs = NA,
        ..factors = NA,
        ..clusters = NA,
        ..structure = NA,
        ..clusters_comb = NA,
        ..factors_comb = NA,
        ..output = NA)
)

datagenResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "datagenResults",
    inherit = jmvcore::Group,
    active = list(
        start = function() private$.items[["start"]],
        help = function() private$.items[["help"]],
        brief = function() private$.items[["brief"]],
        info = function() private$.items[["info"]],
        clusters = function() private$.items[["clusters"]],
        covs = function() private$.items[["covs"]],
        factors = function() private$.items[["factors"]],
        output = function() private$.items[["output"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixed Data Generator")
            self$add(jmvcore::Html$new(
                options=options,
                name="start",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="brief",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Setup Info",
                columns=list(
                    list(
                        `name`="var", 
                        `type`="text", 
                        `title`="Variable", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="name", 
                        `type`="text", 
                        `title`="Name"),
                    list(
                        `name`="feature", 
                        `type`="text", 
                        `title`="Feature"),
                    list(
                        `name`="value", 
                        `type`="integer", 
                        `title`="Value"),
                    list(
                        `name`="structure", 
                        `type`="text", 
                        `title`="Structure"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clusters",
                title="Clusters Info",
                columns=list(
                    list(
                        `name`="Freq", 
                        `type`="number", 
                        `title`="Freq"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="covs",
                title="Numeric Variables Info",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="name", 
                        `type`="text", 
                        `title`="Variable"),
                    list(
                        `name`="mean", 
                        `type`="number", 
                        `title`="Mean", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `type`="number", 
                        `title`="SD", 
                        `format`="zto"),
                    list(
                        `name`="cluster", 
                        `type`="text", 
                        `title`="Cluster"),
                    list(
                        `name`="sd_between", 
                        `type`="number", 
                        `title`="SD between", 
                        `format`="zto"),
                    list(
                        `name`="sd_within", 
                        `type`="number", 
                        `title`="SD within", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="factors",
                title="Factors Info",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="Freq", 
                        `type`="integer", 
                        `title`="Freq"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="output",
                title="New var",
                varDescription="Simulated data",
                initInRun=TRUE))}))

datagenBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "datagenBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "datagen",
                version = c(0,0,1),
                options = options,
                results = datagenResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mixed Model Data Generator
#'
#' Something here
#' 
#' @param data the data as a data frame
#' @param dep .
#' @param dep_n .
#' @param covs .
#' @param factors .
#' @param clusters .
#' @param structure .
#' @param clusters_comb .
#' @param factors_comb .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$start} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$brief} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clusters} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$covs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$factors} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$output} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
datagen <- function(
    data,
    dep,
    dep_n = 50,
    covs = list(),
    factors,
    clusters,
    structure,
    clusters_comb = "cross",
    factors_comb = "cross") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("datagen requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- datagenOptions$new(
        dep = dep,
        dep_n = dep_n,
        covs = covs,
        factors = factors,
        clusters = clusters,
        structure = structure,
        clusters_comb = clusters_comb,
        factors_comb = factors_comb)

    analysis <- datagenClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

