
# This file is automatically generated, you probably don't want to edit this

mixpowerOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixpowerOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "lmer",
            .interface = "jamovi",
            dep = NULL,
            factors = NULL,
            covs = NULL,
            model_terms = NULL,
            fixed_intercept = TRUE,
            nested_terms = NULL,
            comparison = FALSE,
            nested_intercept = TRUE,
            omnibus = "LRT",
            donotrun = FALSE,
            fixed_sizes = NULL,
            re_sizes = NULL,
            contrasts = NULL,
            model_type = "lmer",
            cluster = NULL,
            re = list(
                list()),
            nested_re = list(
                list()),
            re_corr = "all",
            re_modelterms = TRUE,
            re_listing = "none",
            reml = TRUE,
            re_lrt = FALSE,
            df_method = "Satterthwaite", ...) {

            super$initialize(
                package="pamlj",
                name="mixpower",
                requiresData=TRUE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="lmer",
                hidden=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..model_terms <- jmvcore::OptionTerms$new(
                "model_terms",
                model_terms,
                default=NULL)
            private$..fixed_intercept <- jmvcore::OptionBool$new(
                "fixed_intercept",
                fixed_intercept,
                default=TRUE)
            private$..nested_terms <- jmvcore::OptionTerms$new(
                "nested_terms",
                nested_terms,
                default=NULL)
            private$..comparison <- jmvcore::OptionBool$new(
                "comparison",
                comparison,
                default=FALSE)
            private$..nested_intercept <- jmvcore::OptionBool$new(
                "nested_intercept",
                nested_intercept,
                default=TRUE)
            private$..omnibus <- jmvcore::OptionList$new(
                "omnibus",
                omnibus,
                hidden=TRUE,
                default="LRT",
                options=list(
                    "LRT"))
            private$..donotrun <- jmvcore::OptionBool$new(
                "donotrun",
                donotrun,
                default=FALSE)
            private$..fixed_sizes <- jmvcore::OptionArray$new(
                "fixed_sizes",
                fixed_sizes,
                template=jmvcore::OptionGroup$new(
                    "fixed_sizes",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "value",
                            NULL))))
            private$..re_sizes <- jmvcore::OptionArray$new(
                "re_sizes",
                re_sizes,
                template=jmvcore::OptionGroup$new(
                    "re_sizes",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "value",
                            NULL))))
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "simple",
                                "deviation",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..model_type <- jmvcore::OptionList$new(
                "model_type",
                model_type,
                hidden=TRUE,
                options=list(
                    "lmer"),
                default="lmer")
            private$..cluster <- jmvcore::OptionVariables$new(
                "cluster",
                cluster,
                default=NULL,
                suggested=list(
                    "nominal"))
            private$..re <- jmvcore::OptionArray$new(
                "re",
                re,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "re",
                    NULL))
            private$..nested_re <- jmvcore::OptionArray$new(
                "nested_re",
                nested_re,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "nested_re",
                    NULL))
            private$..re_corr <- jmvcore::OptionList$new(
                "re_corr",
                re_corr,
                options=list(
                    "all",
                    "none",
                    "block"),
                default="all")
            private$..re_modelterms <- jmvcore::OptionBool$new(
                "re_modelterms",
                re_modelterms,
                default=TRUE)
            private$..re_listing <- jmvcore::OptionList$new(
                "re_listing",
                re_listing,
                options=list(
                    "none",
                    "main",
                    "way2",
                    "way3",
                    "all"),
                default="none")
            private$..reml <- jmvcore::OptionBool$new(
                "reml",
                reml,
                default=TRUE)
            private$..re_lrt <- jmvcore::OptionBool$new(
                "re_lrt",
                re_lrt,
                default=FALSE)
            private$..df_method <- jmvcore::OptionList$new(
                "df_method",
                df_method,
                default="Satterthwaite",
                options=list(
                    "Satterthwaite",
                    "Kenward-Roger"))

            self$.addOption(private$...caller)
            self$.addOption(private$...interface)
            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..model_terms)
            self$.addOption(private$..fixed_intercept)
            self$.addOption(private$..nested_terms)
            self$.addOption(private$..comparison)
            self$.addOption(private$..nested_intercept)
            self$.addOption(private$..omnibus)
            self$.addOption(private$..donotrun)
            self$.addOption(private$..fixed_sizes)
            self$.addOption(private$..re_sizes)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..model_type)
            self$.addOption(private$..cluster)
            self$.addOption(private$..re)
            self$.addOption(private$..nested_re)
            self$.addOption(private$..re_corr)
            self$.addOption(private$..re_modelterms)
            self$.addOption(private$..re_listing)
            self$.addOption(private$..reml)
            self$.addOption(private$..re_lrt)
            self$.addOption(private$..df_method)
        }),
    active = list(
        .caller = function() private$...caller$value,
        .interface = function() private$...interface$value,
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        model_terms = function() private$..model_terms$value,
        fixed_intercept = function() private$..fixed_intercept$value,
        nested_terms = function() private$..nested_terms$value,
        comparison = function() private$..comparison$value,
        nested_intercept = function() private$..nested_intercept$value,
        omnibus = function() private$..omnibus$value,
        donotrun = function() private$..donotrun$value,
        fixed_sizes = function() private$..fixed_sizes$value,
        re_sizes = function() private$..re_sizes$value,
        contrasts = function() private$..contrasts$value,
        model_type = function() private$..model_type$value,
        cluster = function() private$..cluster$value,
        re = function() private$..re$value,
        nested_re = function() private$..nested_re$value,
        re_corr = function() private$..re_corr$value,
        re_modelterms = function() private$..re_modelterms$value,
        re_listing = function() private$..re_listing$value,
        reml = function() private$..reml$value,
        re_lrt = function() private$..re_lrt$value,
        df_method = function() private$..df_method$value),
    private = list(
        ...caller = NA,
        ...interface = NA,
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..model_terms = NA,
        ..fixed_intercept = NA,
        ..nested_terms = NA,
        ..comparison = NA,
        ..nested_intercept = NA,
        ..omnibus = NA,
        ..donotrun = NA,
        ..fixed_sizes = NA,
        ..re_sizes = NA,
        ..contrasts = NA,
        ..model_type = NA,
        ..cluster = NA,
        ..re = NA,
        ..nested_re = NA,
        ..re_corr = NA,
        ..re_modelterms = NA,
        ..re_listing = NA,
        ..reml = NA,
        ..re_lrt = NA,
        ..df_method = NA)
)

mixpowerResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixpowerResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        start = function() private$.items[["start"]],
        help = function() private$.items[["help"]],
        brief = function() private$.items[["brief"]],
        info = function() private$.items[["info"]],
        main = function() private$.items[["main"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixed Model Power Analysis")
            private$..model <- NULL
            self$add(jmvcore::Html$new(
                options=options,
                name="start",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="brief",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Model Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Info"),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`="")),
                refs="gamlj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    r2 = function() private$.items[["r2"]],
                    anova = function() private$.items[["anova"]],
                    coefficients = function() private$.items[["coefficients"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]],
                    random = function() private$.items[["random"]],
                    randomcov = function() private$.items[["randomcov"]],
                    ranova = function() private$.items[["ranova"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="main",
                            title="Model Results")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="r2",
                            title="Model Fit",
                            clearWith=list(
                                "dep",
                                "model_terms",
                                "nested_terms",
                                "fixed_intercept",
                                "reml",
                                "comparison",
                                "nested_re",
                                "nested_intercept",
                                "re",
                                "re_corr"),
                            rows=1,
                            columns=list(
                                list(
                                    `name`="model", 
                                    `title`="Model", 
                                    `visible`="(comparison)"),
                                list(
                                    `name`="type", 
                                    `type`="text", 
                                    `title`="Type"),
                                list(
                                    `name`="r2", 
                                    `title`="R\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="test", 
                                    `title`="LRT X\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue")),
                            refs="goodness"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="anova",
                            title="Fixed Effects Omnibus Tests",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "dep_scale",
                                "fixed_intercept",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="f", 
                                    `title`="F", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="df2", 
                                    `title`="df (res)", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coefficients",
                            title="Parameter Estimates (Fixed coefficients)",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "dep_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "estimates_ci",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="source", 
                                    `title`="Names", 
                                    `type`="text", 
                                    `visible`="(show_contrastnames)"),
                                list(
                                    `name`="label", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="estimate", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="est.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(estimates_ci)"),
                                list(
                                    `name`="est.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(estimates_ci)"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="t", 
                                    `title`="t", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue")),
                            refs="parameters"))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible="(show_contrastcodes)",
                            items="(factors)",
                            clearWith=list(
                                "contrasts"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="Factor: ___key___",
                                columns=list(
                                    list(
                                        `name`="cname", 
                                        `title`="Name", 
                                        `type`="text", 
                                        `visible`="(show_contrastnames)"),
                                    list(
                                        `name`="clab", 
                                        `title`="Contrast", 
                                        `type`="text"),
                                    list(
                                        `name`="bogus", 
                                        `title`="bogus", 
                                        `type`="text", 
                                        `visible`=FALSE)))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="random",
                            title="Random Components",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "dep_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr",
                                "re_ci"),
                            columns=list(
                                list(
                                    `name`="groups", 
                                    `title`="Groups", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="name", 
                                    `title`="Name", 
                                    `type`="text"),
                                list(
                                    `name`="std", 
                                    `title`="SD", 
                                    `type`="number"),
                                list(
                                    `name`="var", 
                                    `title`="Variance", 
                                    `type`="number"),
                                list(
                                    `name`="var.ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(re_ci)"),
                                list(
                                    `name`="var.ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(re_ci)"),
                                list(
                                    `name`="icc", 
                                    `title`="ICC", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="randomcov",
                            title="Random Parameters correlations",
                            visible=FALSE,
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "dep_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="groups", 
                                    `title`="Groups", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="name", 
                                    `title`="name", 
                                    `type`="text"),
                                list(
                                    `name`="name2", 
                                    `title`="name2", 
                                    `type`="text"),
                                list(
                                    `name`="std", 
                                    `title`="Corr.", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ranova",
                            title="Random Effect LRT",
                            visible="(re_lrt)",
                            clearWith=list(
                                "relm",
                                "dep",
                                "model_terms",
                                "contrasts",
                                "covs_scale",
                                "dep_scale",
                                "fixed_intercept",
                                "ci_width",
                                "ci_method",
                                "boot_r",
                                "df_method",
                                "re",
                                "re_corr"),
                            columns=list(
                                list(
                                    `name`="test", 
                                    `title`="Test", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="npar", 
                                    `title`="N. par", 
                                    `type`="number"),
                                list(
                                    `name`="AIC", 
                                    `title`="AIC", 
                                    `type`="number"),
                                list(
                                    `name`="LRT", 
                                    `title`="LRT", 
                                    `type`="number"),
                                list(
                                    `name`="Df", 
                                    `title`="df", 
                                    `type`="number"),
                                list(
                                    `name`="Pr(>Chisq)", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))},
        .setModel=function(x) private$..model <- x))

mixpowerBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixpowerBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "mixpower",
                version = c(3,0,0),
                options = options,
                results = mixpowerResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Mixed Model Power Analysis
#'
#' Mixed Linear Model
#' 
#'
#' @examples
#' data(subjects_by_stimuli)
#' gamlj::gamljMixed(
#'        formula = y ~ 1 + cond+( 1|subj ),
#'        data = subjects_by_stimuli)
#'
#' @param data the data as a data frame
#' @param .caller .
#' @param .interface .
#' @param dep a string naming the dependent variable from \code{data}; the
#'   variable must be numeric. Not needed if \code{formula} is used.
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}. Not needed if \code{formula} is used.
#' @param covs a vector of strings naming the covariates from \code{data}. Not
#'   needed if \code{formula} is used.
#' @param model_terms a list of character vectors describing fixed effects
#'   terms. Not needed if \code{formula} is used.
#' @param fixed_intercept \code{TRUE} (default) or \code{FALSE}, estimates
#'   fixed intercept. Not needed if \code{formula} is used.
#' @param nested_terms a list of character vectors describing effects terms
#'   for nestet. It can be passed as right-hand formula.
#' @param comparison Not present in R
#' @param nested_intercept \code{TRUE} (default) or \code{FALSE}, estimates
#'   fixed intercept. Not needed if \code{formula} is used.
#' @param omnibus \code{TRUE} (default) or \code{FALSE}, estimates fixed
#'   intercept. Not needed if \code{formula} is used.
#' @param donotrun .
#' @param fixed_sizes .
#' @param re_sizes .
#' @param contrasts a named vector of the form \code{c(var1="type",
#'   var2="type2")} specifying the type of contrast to use, one of
#'   \code{'deviation'}, \code{'simple'}, \code{'dummy'}, \code{'difference'},
#'   \code{'helmert'}, \code{'repeated'} or \code{'polynomial'}. If NULL,
#'   \code{simple} is used. Can also be passed as a list of list of the form
#'   list(list(var="var1",type="type1")).
#' @param model_type .
#' @param cluster a vector of strings naming the clustering variables from
#'   \code{data}
#' @param re a list of lists specifying the models random effects.
#' @param nested_re a list of lists specifying the models random effects.
#' @param re_corr \code{'all'}, \code{'none'} (default), or \code{'block'}.
#'   When random effects are passed as list of length 1, it decides whether the
#'   effects should be correlated,  non correlated. If \code{'re'} is a list of
#'   lists of length > 1, the option is automatially set to \code{'block'}. The
#'   option is ignored if the model is passed using \code{formula}.
#' @param re_modelterms Not in R interface
#' @param re_listing Not in R interface
#' @param reml \code{TRUE} (default) or \code{FALSE}, should the Restricted ML
#'   be used rather than ML
#' @param re_lrt \code{TRUE} or \code{FALSE} (default), LRT for the random
#'   effects
#' @param df_method .
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab a property \cr
#'   \code{results$start} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$brief} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$r2} \tab \tab \tab \tab \tab a table of R \cr
#'   \code{results$main$anova} \tab \tab \tab \tab \tab a table of ANOVA results \cr
#'   \code{results$main$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$contrastCodeTables} \tab \tab \tab \tab \tab an array of contrast coefficients tables \cr
#'   \code{results$main$random} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$randomcov} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$main$ranova} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
mixpower <- function(
    data,
    .caller = "lmer",
    .interface = "jamovi",
    dep = NULL,
    factors = NULL,
    covs = NULL,
    model_terms = NULL,
    fixed_intercept = TRUE,
    nested_terms = NULL,
    comparison = FALSE,
    nested_intercept = TRUE,
    omnibus = "LRT",
    donotrun = FALSE,
    fixed_sizes,
    re_sizes,
    contrasts = NULL,
    model_type = "lmer",
    cluster = NULL,
    re = list(
                list()),
    nested_re = list(
                list()),
    re_corr = "all",
    re_modelterms = TRUE,
    re_listing = "none",
    reml = TRUE,
    re_lrt = FALSE,
    df_method = "Satterthwaite",
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mixpower requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(dep))
            dep <- mixpowerClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="dep")
        if (missing(factors))
            factors <- mixpowerClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="factors")
        if (missing(covs))
            covs <- mixpowerClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="covs")
        if (missing(cluster))
            cluster <- mixpowerClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="cluster")
        if (missing(re))
            re <- mixpowerClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="re")
        if (missing(model_terms))
            model_terms <- mixpowerClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="model_terms")
    }

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(cluster)) cluster <- jmvcore::resolveQuo(jmvcore::enquo(cluster))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(cluster), cluster, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    if (inherits(model_terms, "formula")) model_terms <- jmvcore::decomposeFormula(model_terms)
    if (inherits(nested_terms, "formula")) nested_terms <- jmvcore::decomposeFormula(nested_terms)

    options <- mixpowerOptions$new(
        .caller = .caller,
        .interface = .interface,
        dep = dep,
        factors = factors,
        covs = covs,
        model_terms = model_terms,
        fixed_intercept = fixed_intercept,
        nested_terms = nested_terms,
        comparison = comparison,
        nested_intercept = nested_intercept,
        omnibus = omnibus,
        donotrun = donotrun,
        fixed_sizes = fixed_sizes,
        re_sizes = re_sizes,
        contrasts = contrasts,
        model_type = model_type,
        cluster = cluster,
        re = re,
        nested_re = nested_re,
        re_corr = re_corr,
        re_modelterms = re_modelterms,
        re_listing = re_listing,
        reml = reml,
        re_lrt = re_lrt,
        df_method = df_method)

    analysis <- mixpowerClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

