
# This file is automatically generated, you probably don't want to edit this

pamlfactorialOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlfactorialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aim = "n",
            means = NULL,
            sds = NULL,
            factors = NULL,
            power = 0.9,
            n = 20,
            sig.level = 0.05,
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE,
            plot_log = FALSE,
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 0,
            plot_z_value = list(),
            plot_to_table = FALSE,
            .caller = "factorial",
            gncp = TRUE,
            emeans = FALSE,
            esos = FALSE, ...) {

            super$initialize(
                package="pamlj",
                name="pamlfactorial",
                requiresData=TRUE,
                ...)

            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power"))
            private$..means <- jmvcore::OptionVariable$new(
                "means",
                means,
                default=NULL,
                permitted=list(
                    "numeric"))
            private$..sds <- jmvcore::OptionVariable$new(
                "sds",
                sds,
                default=NULL,
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=20)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=FALSE)
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=0)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..plot_to_table <- jmvcore::OptionBool$new(
                "plot_to_table",
                plot_to_table,
                default=FALSE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="factorial",
                hidden=TRUE)
            private$..gncp <- jmvcore::OptionBool$new(
                "gncp",
                gncp,
                default=TRUE)
            private$..emeans <- jmvcore::OptionBool$new(
                "emeans",
                emeans,
                default=FALSE)
            private$..esos <- jmvcore::OptionBool$new(
                "esos",
                esos,
                default=FALSE)

            self$.addOption(private$..aim)
            self$.addOption(private$..means)
            self$.addOption(private$..sds)
            self$.addOption(private$..factors)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..plot_to_table)
            self$.addOption(private$...caller)
            self$.addOption(private$..gncp)
            self$.addOption(private$..emeans)
            self$.addOption(private$..esos)
        }),
    active = list(
        aim = function() private$..aim$value,
        means = function() private$..means$value,
        sds = function() private$..sds$value,
        factors = function() private$..factors$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        sig.level = function() private$..sig.level$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        plot_to_table = function() private$..plot_to_table$value,
        .caller = function() private$...caller$value,
        gncp = function() private$..gncp$value,
        emeans = function() private$..emeans$value,
        esos = function() private$..esos$value),
    private = list(
        ..aim = NA,
        ..means = NA,
        ..sds = NA,
        ..factors = NA,
        ..power = NA,
        ..n = NA,
        ..sig.level = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..plot_to_table = NA,
        ...caller = NA,
        ..gncp = NA,
        ..emeans = NA,
        ..esos = NA)
)

pamlfactorialResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlfactorialResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        issues = function() private$.items[["issues"]],
        powertab = function() private$.items[["powertab"]],
        effectsize = function() private$.items[["effectsize"]],
        powerbyes = function() private$.items[["powerbyes"]],
        means = function() private$.items[["means"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        powerCustom = function() private$.items[["powerCustom"]],
        plotnotes = function() private$.items[["plotnotes"]],
        customtable = function() private$.items[["customtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Factorial designs power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "factors",
                    "means",
                    "sds"),
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="ss", 
                        `title`="SS", 
                        `type`="number", 
                        `visible`="(esos)"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="f2", 
                        `title`="f\u00B2", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df_model", 
                        `title`="df(model)", 
                        `type`="integer"),
                    list(
                        `name`="df1", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="df(res)", 
                        `type`="integer"),
                    list(
                        `name`="sig.level", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectsize",
                title="Computed Parameters",
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "factors",
                    "means",
                    "sds"),
                columns=list(
                    list(
                        `name`="index", 
                        `title`="Index", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "factors",
                    "means",
                    "sds"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="means",
                title="Expected Marginal Means",
                visible="(emeans)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Marginal Means - ___key___",
                    columns=list(
                        list(
                            `name`="emmean", 
                            `title`="Mean", 
                            `type`="number"),
                        list(
                            `name`="sd", 
                            `title`="SD", 
                            `type`="number")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !aim:n)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !aim:es)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="customtable",
                title="Power Analysis parameters",
                visible="(plot_to_table && !plot_x:none && !plot_y:none)",
                columns=list(
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number", 
                        `visible`=FALSE),
                    list(
                        `name`="n1", 
                        `title`="N\u2081", 
                        `type`="integer", 
                        `visible`=FALSE),
                    list(
                        `name`="n2", 
                        `title`="N\u2082", 
                        `type`="integer", 
                        `visible`=FALSE))))}))

pamlfactorialBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlfactorialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlfactorial",
                version = c(0,0,1),
                options = options,
                results = pamlfactorialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Factorial Designs
#'
#' Something here
#' 
#' @param data the data as a data frame
#' @param aim The aim of the analysis: \code{n} (default) for sample size,
#'   \code{power} to estimate power
#' @param means a string naming the variable containing the means from
#'   \code{data}; the variable must be numeric.
#' @param sds a string naming the variable containing the standard deviations
#'   from \code{data}; the variable must be numeric.
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}. Not needed if \code{formula} is used.
#' @param power Minimal desired power
#' @param n Sample size
#' @param sig.level Type I error rate (significance cut-off or alpha)
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @param plot_log .
#' @param plot_x .
#' @param plot_y .
#' @param plot_custom_labels .
#' @param plot_z .
#' @param plot_x_from .
#' @param plot_x_to .
#' @param plot_z_lines .
#' @param plot_z_value .
#' @param plot_to_table .
#' @param .caller Used for internal purposes
#' @param gncp .
#' @param emeans .
#' @param esos .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effectsize} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$means} \tab \tab \tab \tab \tab an array of predicted means tables \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$customtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlfactorial <- function(
    data,
    aim = "n",
    means = NULL,
    sds = NULL,
    factors = NULL,
    power = 0.9,
    n = 20,
    sig.level = 0.05,
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE,
    plot_log = FALSE,
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 0,
    plot_z_value = list(),
    plot_to_table = FALSE,
    .caller = "factorial",
    gncp = TRUE,
    emeans = FALSE,
    esos = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlfactorial requires jmvcore to be installed (restart may be required)")

    if ( ! missing(means)) means <- jmvcore::resolveQuo(jmvcore::enquo(means))
    if ( ! missing(sds)) sds <- jmvcore::resolveQuo(jmvcore::enquo(sds))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(means), means, NULL),
            `if`( ! missing(sds), sds, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- pamlfactorialOptions$new(
        aim = aim,
        means = means,
        sds = sds,
        factors = factors,
        power = power,
        n = n,
        sig.level = sig.level,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        plot_to_table = plot_to_table,
        .caller = .caller,
        gncp = gncp,
        emeans = emeans,
        esos = esos)

    analysis <- pamlfactorialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

