
# This file is automatically generated, you probably don't want to edit this

pamlmixedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmixedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aim = "n",
            find = "k",
            code = "",
            fonts = "small",
            toggle = FALSE,
            sigma2 = 1,
            power = 0.9,
            sig.level = 0.05,
            mcR = 500,
            parallel = TRUE,
            tol = 0.01,
            set_seed = FALSE,
            seed = 42,
            stability = "l1",
            .interface = "jamovi",
            .caller = "pamlmixed",
            clusterpars = list(),
            var_type = list(), ...) {

            super$initialize(
                package="pamlj",
                name="pamlmixed",
                requiresData=FALSE,
                ...)

            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power"))
            private$..find <- jmvcore::OptionList$new(
                "find",
                find,
                default="k",
                options=list(
                    "k",
                    "n"))
            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                hidden=TRUE,
                default="")
            private$..fonts <- jmvcore::OptionString$new(
                "fonts",
                fonts,
                default="small",
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)
            private$..run <- jmvcore::OptionAction$new(
                "run",
                FALSE,
                hidden=TRUE)
            private$..sigma2 <- jmvcore::OptionNumber$new(
                "sigma2",
                sigma2,
                default=1)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..mcR <- jmvcore::OptionNumber$new(
                "mcR",
                mcR,
                default=500)
            private$..parallel <- jmvcore::OptionBool$new(
                "parallel",
                parallel,
                default=TRUE)
            private$..tol <- jmvcore::OptionNumber$new(
                "tol",
                tol,
                default=0.01)
            private$..set_seed <- jmvcore::OptionBool$new(
                "set_seed",
                set_seed,
                default=FALSE)
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=42)
            private$..stability <- jmvcore::OptionList$new(
                "stability",
                stability,
                default="l1",
                options=list(
                    "l1",
                    "l2"))
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="pamlmixed",
                hidden=TRUE)
            private$..clusterpars <- jmvcore::OptionArray$new(
                "clusterpars",
                clusterpars,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "clusterpars",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionString$new(
                            "k",
                            NULL),
                        jmvcore::OptionString$new(
                            "n",
                            NULL))))
            private$..var_type <- jmvcore::OptionArray$new(
                "var_type",
                var_type,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "var_type",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "categorical",
                                "continuous"),
                            default="continuous"),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL))))

            self$.addOption(private$..aim)
            self$.addOption(private$..find)
            self$.addOption(private$..code)
            self$.addOption(private$..fonts)
            self$.addOption(private$..toggle)
            self$.addOption(private$..run)
            self$.addOption(private$..sigma2)
            self$.addOption(private$..power)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..mcR)
            self$.addOption(private$..parallel)
            self$.addOption(private$..tol)
            self$.addOption(private$..set_seed)
            self$.addOption(private$..seed)
            self$.addOption(private$..stability)
            self$.addOption(private$...interface)
            self$.addOption(private$...caller)
            self$.addOption(private$..clusterpars)
            self$.addOption(private$..var_type)
        }),
    active = list(
        aim = function() private$..aim$value,
        find = function() private$..find$value,
        code = function() private$..code$value,
        fonts = function() private$..fonts$value,
        toggle = function() private$..toggle$value,
        run = function() private$..run$value,
        sigma2 = function() private$..sigma2$value,
        power = function() private$..power$value,
        sig.level = function() private$..sig.level$value,
        mcR = function() private$..mcR$value,
        parallel = function() private$..parallel$value,
        tol = function() private$..tol$value,
        set_seed = function() private$..set_seed$value,
        seed = function() private$..seed$value,
        stability = function() private$..stability$value,
        .interface = function() private$...interface$value,
        .caller = function() private$...caller$value,
        clusterpars = function() private$..clusterpars$value,
        var_type = function() private$..var_type$value),
    private = list(
        ..aim = NA,
        ..find = NA,
        ..code = NA,
        ..fonts = NA,
        ..toggle = NA,
        ..run = NA,
        ..sigma2 = NA,
        ..power = NA,
        ..sig.level = NA,
        ..mcR = NA,
        ..parallel = NA,
        ..tol = NA,
        ..set_seed = NA,
        ..seed = NA,
        ..stability = NA,
        ...interface = NA,
        ...caller = NA,
        ..clusterpars = NA,
        ..var_type = NA)
)

pamlmixedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmixedResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        extrainfo = function() private$.items[["extrainfo"]],
        issues = function() private$.items[["issues"]],
        initnotes = function() private$.items[["initnotes"]],
        infotab = function() private$.items[["infotab"]],
        powertab = function() private$.items[["powertab"]],
        effectsizes = function() private$.items[["effectsizes"]],
        plotnotes = function() private$.items[["plotnotes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixed Models Power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="extrainfo",
                title="Extra Info",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="initnotes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="infotab",
                title="Model Information",
                columns=list(
                    list(
                        `name`="info", 
                        `title`="Info", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="value", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="specs", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="Estimate", 
                        `type`="text"),
                    list(
                        `name`="k", 
                        `title`="Cluster levels", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="N per cluster", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="df_error", 
                        `title`="df_error", 
                        `type`="number"),
                    list(
                        `name`="sig.level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="converged", 
                        `title`="% converged", 
                        `type`="number"),
                    list(
                        `name`="singular", 
                        `title`="% singular", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectsizes",
                title="Effect size indices",
                rows=1,
                columns=list(
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Input", 
                        `type`="number"),
                    list(
                        `name`="es", 
                        `title`="ES", 
                        `type`="number"),
                    list(
                        `name`="cluster", 
                        `title`="Cluster", 
                        `type`="text"),
                    list(
                        `name`="label", 
                        `title`="ES label", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))}))

pamlmixedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmixedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlmixed",
                version = c(0,5,0),
                options = options,
                results = pamlmixedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

