
# This file is automatically generated, you probably don't want to edit this

pamlcorrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlcorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "correlation",
            aim = "n",
            es = 0.5,
            power = 0.9,
            sample = 20,
            alpha = 0.05,
            tails = "two",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE, ...) {

            super$initialize(
                package="pamlj",
                name="pamlcorr",
                requiresData=FALSE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="correlation",
                hidden=TRUE)
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                default=0.5)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sample <- jmvcore::OptionNumber$new(
                "sample",
                sample,
                default=20)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..tails <- jmvcore::OptionList$new(
                "tails",
                tails,
                default="two",
                options=list(
                    "two",
                    "one"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)

            self$.addOption(private$...caller)
            self$.addOption(private$..aim)
            self$.addOption(private$..es)
            self$.addOption(private$..power)
            self$.addOption(private$..sample)
            self$.addOption(private$..alpha)
            self$.addOption(private$..tails)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
        }),
    active = list(
        .caller = function() private$...caller$value,
        aim = function() private$..aim$value,
        es = function() private$..es$value,
        power = function() private$..power$value,
        sample = function() private$..sample$value,
        alpha = function() private$..alpha$value,
        tails = function() private$..tails$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value),
    private = list(
        ...caller = NA,
        ..aim = NA,
        ..es = NA,
        ..power = NA,
        ..sample = NA,
        ..alpha = NA,
        ..tails = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA)
)

pamlcorrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlcorrResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        issues = function() private$.items[["issues"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="alpha", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)",
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !aim:n)",
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !aim:es)",
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails")))}))

pamlcorrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlcorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlcorr",
                version = c(0,0,1),
                options = options,
                results = pamlcorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Correlation
#'
#' Something here
#' 
#' @param .caller .
#' @param aim .
#' @param es .
#' @param power .
#' @param sample .
#' @param alpha .
#' @param tails .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlcorr <- function(
    .caller = "correlation",
    aim = "n",
    es = 0.5,
    power = 0.9,
    sample = 20,
    alpha = 0.05,
    tails = "two",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlcorr requires jmvcore to be installed (restart may be required)")


    options <- pamlcorrOptions$new(
        .caller = .caller,
        aim = aim,
        es = es,
        power = power,
        sample = sample,
        alpha = alpha,
        tails = tails,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve)

    analysis <- pamlcorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

