
# This file is automatically generated, you probably don't want to edit this

pamlgzlmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlgzlmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            model_type = NULL,
            aim = "n",
            mode = "eta",
            r2_es = 0.05,
            r2_df = 1,
            eta_es = 0.1,
            eta_df = 1,
            y_levels = 2,
            y_prop = 0.5,
            power = 0.9,
            n = 20,
            sig.level = 0.05,
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE,
            plot_log = FALSE,
            plot_palette = "viridis",
            covs = 0,
            factors = 0,
            factors_list = list(
                list(var="factor 1", levels=0)),
            covs_order = "main",
            factors_order = "main",
            mixed_order = "none",
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 0,
            plot_z_value = list(),
            plot_to_table = FALSE,
            explain = FALSE,
            .caller = "gzlm",
            .interface = "jamovi", ...) {

            super$initialize(
                package="pamlj",
                name="pamlgzlm",
                requiresData=TRUE,
                ...)

            private$..model_type <- jmvcore::OptionList$new(
                "model_type",
                model_type,
                options=list(
                    "logistic",
                    "ordinal",
                    "multinomial"))
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "eta",
                    "r2"),
                default="eta")
            private$..r2_es <- jmvcore::OptionNumber$new(
                "r2_es",
                r2_es,
                default=0.05)
            private$..r2_df <- jmvcore::OptionNumber$new(
                "r2_df",
                r2_df,
                default=1,
                min=0)
            private$..eta_es <- jmvcore::OptionNumber$new(
                "eta_es",
                eta_es,
                default=0.1)
            private$..eta_df <- jmvcore::OptionNumber$new(
                "eta_df",
                eta_df,
                default=1,
                min=1)
            private$..y_levels <- jmvcore::OptionNumber$new(
                "y_levels",
                y_levels,
                default=2,
                min=2)
            private$..y_prop <- jmvcore::OptionNumber$new(
                "y_prop",
                y_prop,
                default=0.5,
                min=0,
                max=0.9)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=20)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=FALSE)
            private$..plot_palette <- jmvcore::OptionList$new(
                "plot_palette",
                plot_palette,
                default="viridis",
                options=list(
                    "viridis",
                    "rocket",
                    "mako",
                    "cividis",
                    "plasma",
                    "turbo",
                    "husky"))
            private$..covs <- jmvcore::OptionNumber$new(
                "covs",
                covs,
                default=0,
                min=0)
            private$..factors <- jmvcore::OptionNumber$new(
                "factors",
                factors,
                default=0,
                min=0)
            private$..factors_list <- jmvcore::OptionArray$new(
                "factors_list",
                factors_list,
                default=list(
                    list(var="factor 1", levels=0)),
                template=jmvcore::OptionGroup$new(
                    "factors_list",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionInteger$new(
                            "levels",
                            NULL))))
            private$..covs_order <- jmvcore::OptionList$new(
                "covs_order",
                covs_order,
                default="main",
                options=list(
                    "main",
                    "order2",
                    "order3",
                    "orderall"))
            private$..factors_order <- jmvcore::OptionList$new(
                "factors_order",
                factors_order,
                default="main",
                options=list(
                    "main",
                    "order2",
                    "order3",
                    "orderall"))
            private$..mixed_order <- jmvcore::OptionList$new(
                "mixed_order",
                mixed_order,
                default="none",
                options=list(
                    "none",
                    "order2",
                    "order3",
                    "orderall"))
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=0)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..plot_to_table <- jmvcore::OptionBool$new(
                "plot_to_table",
                plot_to_table,
                default=FALSE)
            private$..explain <- jmvcore::OptionBool$new(
                "explain",
                explain,
                default=FALSE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="gzlm",
                hidden=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)

            self$.addOption(private$..model_type)
            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..r2_es)
            self$.addOption(private$..r2_df)
            self$.addOption(private$..eta_es)
            self$.addOption(private$..eta_df)
            self$.addOption(private$..y_levels)
            self$.addOption(private$..y_prop)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..plot_palette)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..factors_list)
            self$.addOption(private$..covs_order)
            self$.addOption(private$..factors_order)
            self$.addOption(private$..mixed_order)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..plot_to_table)
            self$.addOption(private$..explain)
            self$.addOption(private$...caller)
            self$.addOption(private$...interface)
        }),
    active = list(
        model_type = function() private$..model_type$value,
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        r2_es = function() private$..r2_es$value,
        r2_df = function() private$..r2_df$value,
        eta_es = function() private$..eta_es$value,
        eta_df = function() private$..eta_df$value,
        y_levels = function() private$..y_levels$value,
        y_prop = function() private$..y_prop$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        sig.level = function() private$..sig.level$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        plot_palette = function() private$..plot_palette$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        factors_list = function() private$..factors_list$value,
        covs_order = function() private$..covs_order$value,
        factors_order = function() private$..factors_order$value,
        mixed_order = function() private$..mixed_order$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        plot_to_table = function() private$..plot_to_table$value,
        explain = function() private$..explain$value,
        .caller = function() private$...caller$value,
        .interface = function() private$...interface$value),
    private = list(
        ..model_type = NA,
        ..aim = NA,
        ..mode = NA,
        ..r2_es = NA,
        ..r2_df = NA,
        ..eta_es = NA,
        ..eta_df = NA,
        ..y_levels = NA,
        ..y_prop = NA,
        ..power = NA,
        ..n = NA,
        ..sig.level = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..plot_palette = NA,
        ..covs = NA,
        ..factors = NA,
        ..factors_list = NA,
        ..covs_order = NA,
        ..factors_order = NA,
        ..mixed_order = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..plot_to_table = NA,
        ..explain = NA,
        ...caller = NA,
        ...interface = NA)
)

pamlgzlmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlgzlmResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        extrainfo = function() private$.items[["extrainfo"]],
        issues = function() private$.items[["issues"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        plotnotes = function() private$.items[["plotnotes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        powerCustom = function() private$.items[["powerCustom"]],
        customnotes = function() private$.items[["customnotes"]],
        customtable = function() private$.items[["customtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Power: Generalized Linear Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="extrainfo",
                title="Extra Info",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="Power Analysis Results",
                rows=1,
                refs=list(
                    "pamlj"),
                clearWith=list(
                    "mode",
                    "eta_es",
                    "eta_df",
                    "r2_es",
                    "r2_df",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "covs",
                    "factors",
                    "factors_list",
                    "covs_order",
                    "factors_order",
                    "mixed_order"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="sig.level", 
                        `title`="\u03B1", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "mode",
                    "eta_es",
                    "eta_df_model",
                    "r2_es",
                    "r2_df_model",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "covs",
                    "factors",
                    "factors_list",
                    "covs_order",
                    "factors_order",
                    "mixed_order"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=500,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)",
                clearWith=list(
                    "mode",
                    "eta_es",
                    "eta_df_model",
                    "r2_es",
                    "r2_df_model",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "plot_log",
                    "plot_palette",
                    "covs",
                    "factors",
                    "factors_list",
                    "covs_order",
                    "factors_order",
                    "mixed_order")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve)",
                clearWith=list(
                    "mode",
                    "eta_es",
                    "eta_df_model",
                    "r2_es",
                    "r2_df_model",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "plot_log",
                    "plot_palette",
                    "covs",
                    "factors",
                    "factors_list",
                    "covs_order",
                    "factors_order",
                    "mixed_order")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve)",
                clearWith=list(
                    "mode",
                    "eta_es",
                    "eta_df_model",
                    "r2_es",
                    "r2_df_model",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "plot_log",
                    "plot_palette",
                    "covs",
                    "factors",
                    "factors_list",
                    "covs_order",
                    "factors_order",
                    "mixed_order")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="customnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="customtable",
                title="Power Analysis parameters",
                visible="(plot_to_table && !plot_x:none && !plot_y:none)",
                columns=list(
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number", 
                        `visible`=FALSE),
                    list(
                        `name`="n1", 
                        `title`="N\u2081", 
                        `type`="integer", 
                        `visible`=FALSE),
                    list(
                        `name`="n2", 
                        `title`="N\u2082", 
                        `type`="integer", 
                        `visible`=FALSE))))}))

pamlgzlmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlgzlmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlgzlm",
                version = c(0,0,1),
                options = options,
                results = pamlgzlmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

