
# This file is automatically generated, you probably don't want to edit this

pamlglmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aim = "n",
            mode = "peta",
            b_es = 0.2,
            b_r2 = 0.05,
            b_df_model = 1,
            v_es = 0.2,
            v_df_model = 1,
            v_df_effect = 1,
            e_es = 0.2,
            e_df_model = 1,
            e_r2 = 0.2,
            e_df_effect = 1,
            power = 0.9,
            n = 20,
            sig.level = 0.05,
            alternative = "two.sided",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE,
            plot_log = FALSE,
            covs = 0,
            factors = 0,
            factors_list = list(
                list(var="factor 1", levels=0)),
            covs_order = NULL,
            factors_order = NULL,
            mixed_order = NULL,
            eta = 0.2,
            eta_df_error = 0,
            epsilon = 0,
            omega = 0,
            gpower = 0,
            f2 = 0,
            use = "none",
            ncp_type = NULL,
            rx = NULL,
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 0,
            plot_z_value = list(),
            plot_to_table = FALSE,
            explain = FALSE,
            .caller = "glm",
            .interface = "jamovi", ...) {

            super$initialize(
                package="pamlj",
                name="pamlglm",
                requiresData=TRUE,
                ...)

            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "peta",
                    "eta",
                    "beta"),
                default="peta")
            private$..b_es <- jmvcore::OptionNumber$new(
                "b_es",
                b_es,
                default=0.2)
            private$..b_r2 <- jmvcore::OptionNumber$new(
                "b_r2",
                b_r2,
                default=0.05)
            private$..b_df_model <- jmvcore::OptionNumber$new(
                "b_df_model",
                b_df_model,
                default=1,
                min=0)
            private$..v_es <- jmvcore::OptionNumber$new(
                "v_es",
                v_es,
                default=0.2)
            private$..v_df_model <- jmvcore::OptionNumber$new(
                "v_df_model",
                v_df_model,
                default=1,
                min=1)
            private$..v_df_effect <- jmvcore::OptionNumber$new(
                "v_df_effect",
                v_df_effect,
                default=1,
                min=1)
            private$..e_es <- jmvcore::OptionNumber$new(
                "e_es",
                e_es,
                default=0.2)
            private$..e_df_model <- jmvcore::OptionNumber$new(
                "e_df_model",
                e_df_model,
                default=1,
                min=1)
            private$..e_r2 <- jmvcore::OptionNumber$new(
                "e_r2",
                e_r2,
                default=0.2)
            private$..e_df_effect <- jmvcore::OptionNumber$new(
                "e_df_effect",
                e_df_effect,
                default=1,
                min=1)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=20)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                default="two.sided",
                options=list(
                    "two.sided",
                    "one.sided"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=FALSE)
            private$..covs <- jmvcore::OptionNumber$new(
                "covs",
                covs,
                default=0,
                min=0)
            private$..factors <- jmvcore::OptionNumber$new(
                "factors",
                factors,
                default=0,
                min=0)
            private$..factors_list <- jmvcore::OptionArray$new(
                "factors_list",
                factors_list,
                default=list(
                    list(var="factor 1", levels=0)),
                template=jmvcore::OptionGroup$new(
                    "factors_list",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionInteger$new(
                            "levels",
                            NULL))))
            private$..covs_order <- jmvcore::OptionList$new(
                "covs_order",
                covs_order,
                options=list(
                    "main",
                    "order2",
                    "order3",
                    "orderall"))
            private$..factors_order <- jmvcore::OptionList$new(
                "factors_order",
                factors_order,
                options=list(
                    "main",
                    "order2",
                    "order3",
                    "orderall"))
            private$..mixed_order <- jmvcore::OptionList$new(
                "mixed_order",
                mixed_order,
                options=list(
                    "none",
                    "order2",
                    "order3",
                    "orderall"))
            private$..eta <- jmvcore::OptionNumber$new(
                "eta",
                eta,
                default=0.2)
            private$..eta_df_error <- jmvcore::OptionNumber$new(
                "eta_df_error",
                eta_df_error,
                default=0)
            private$..epsilon <- jmvcore::OptionNumber$new(
                "epsilon",
                epsilon,
                default=0)
            private$..omega <- jmvcore::OptionNumber$new(
                "omega",
                omega,
                default=0)
            private$..gpower <- jmvcore::OptionNumber$new(
                "gpower",
                gpower,
                default=0)
            private$..f2 <- jmvcore::OptionNumber$new(
                "f2",
                f2,
                default=0)
            private$..use <- jmvcore::OptionList$new(
                "use",
                use,
                options=list(
                    "none",
                    "omega",
                    "epsilon",
                    "gpower",
                    "f2"),
                default="none")
            private$..ncp_type <- jmvcore::OptionList$new(
                "ncp_type",
                ncp_type,
                options=list(
                    "gpower",
                    "liberal",
                    "strict"))
            private$..rx <- jmvcore::OptionVariables$new(
                "rx",
                rx,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=0)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..plot_to_table <- jmvcore::OptionBool$new(
                "plot_to_table",
                plot_to_table,
                default=FALSE)
            private$..explain <- jmvcore::OptionBool$new(
                "explain",
                explain,
                default=FALSE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="glm",
                hidden=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)

            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..b_es)
            self$.addOption(private$..b_r2)
            self$.addOption(private$..b_df_model)
            self$.addOption(private$..v_es)
            self$.addOption(private$..v_df_model)
            self$.addOption(private$..v_df_effect)
            self$.addOption(private$..e_es)
            self$.addOption(private$..e_df_model)
            self$.addOption(private$..e_r2)
            self$.addOption(private$..e_df_effect)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..alternative)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..factors_list)
            self$.addOption(private$..covs_order)
            self$.addOption(private$..factors_order)
            self$.addOption(private$..mixed_order)
            self$.addOption(private$..eta)
            self$.addOption(private$..eta_df_error)
            self$.addOption(private$..epsilon)
            self$.addOption(private$..omega)
            self$.addOption(private$..gpower)
            self$.addOption(private$..f2)
            self$.addOption(private$..use)
            self$.addOption(private$..ncp_type)
            self$.addOption(private$..rx)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..plot_to_table)
            self$.addOption(private$..explain)
            self$.addOption(private$...caller)
            self$.addOption(private$...interface)
        }),
    active = list(
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        b_es = function() private$..b_es$value,
        b_r2 = function() private$..b_r2$value,
        b_df_model = function() private$..b_df_model$value,
        v_es = function() private$..v_es$value,
        v_df_model = function() private$..v_df_model$value,
        v_df_effect = function() private$..v_df_effect$value,
        e_es = function() private$..e_es$value,
        e_df_model = function() private$..e_df_model$value,
        e_r2 = function() private$..e_r2$value,
        e_df_effect = function() private$..e_df_effect$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        sig.level = function() private$..sig.level$value,
        alternative = function() private$..alternative$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        factors_list = function() private$..factors_list$value,
        covs_order = function() private$..covs_order$value,
        factors_order = function() private$..factors_order$value,
        mixed_order = function() private$..mixed_order$value,
        eta = function() private$..eta$value,
        eta_df_error = function() private$..eta_df_error$value,
        epsilon = function() private$..epsilon$value,
        omega = function() private$..omega$value,
        gpower = function() private$..gpower$value,
        f2 = function() private$..f2$value,
        use = function() private$..use$value,
        ncp_type = function() private$..ncp_type$value,
        rx = function() private$..rx$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        plot_to_table = function() private$..plot_to_table$value,
        explain = function() private$..explain$value,
        .caller = function() private$...caller$value,
        .interface = function() private$...interface$value),
    private = list(
        ..aim = NA,
        ..mode = NA,
        ..b_es = NA,
        ..b_r2 = NA,
        ..b_df_model = NA,
        ..v_es = NA,
        ..v_df_model = NA,
        ..v_df_effect = NA,
        ..e_es = NA,
        ..e_df_model = NA,
        ..e_r2 = NA,
        ..e_df_effect = NA,
        ..power = NA,
        ..n = NA,
        ..sig.level = NA,
        ..alternative = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..covs = NA,
        ..factors = NA,
        ..factors_list = NA,
        ..covs_order = NA,
        ..factors_order = NA,
        ..mixed_order = NA,
        ..eta = NA,
        ..eta_df_error = NA,
        ..epsilon = NA,
        ..omega = NA,
        ..gpower = NA,
        ..f2 = NA,
        ..use = NA,
        ..ncp_type = NA,
        ..rx = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..plot_to_table = NA,
        ..explain = NA,
        ...caller = NA,
        ...interface = NA)
)

pamlglmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        extrainfo = function() private$.items[["extrainfo"]],
        issues = function() private$.items[["issues"]],
        powertab = function() private$.items[["powertab"]],
        effectsize = function() private$.items[["effectsize"]],
        powerbyes = function() private$.items[["powerbyes"]],
        plotnotes = function() private$.items[["plotnotes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        powerCustom = function() private$.items[["powerCustom"]],
        customnotes = function() private$.items[["customnotes"]],
        customtable = function() private$.items[["customtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Power: General Linear Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="extrainfo",
                title="Extra Info",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                refs=list(
                    "pamlj"),
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "e_es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "b_df_model",
                    "v_df_model",
                    "e_df_model",
                    "b_df_effect",
                    "v_df_effect",
                    "e_df_effect",
                    "e_r2",
                    "v_r2",
                    "b_r2",
                    "ncp_type",
                    "rx",
                    "ry"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="f2", 
                        `title`="f\u00B2", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="df(res)", 
                        `type`="integer"),
                    list(
                        `name`="sig.level", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectsize",
                title="Computed Parameters",
                visible="(mode:beta || mode:eta)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "e_es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "b_df_model",
                    "v_df_model",
                    "e_df_model",
                    "b_df_effect",
                    "v_df_effect",
                    "e_df_effect",
                    "e_r2",
                    "v_r2",
                    "b_r2",
                    "ncp_type",
                    "rx",
                    "ry",
                    "ncp_type"),
                columns=list(
                    list(
                        `name`="index", 
                        `title`="Index", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "e_es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "b_df_model",
                    "v_df_model",
                    "e_df_model",
                    "b_df_effect",
                    "v_df_effect",
                    "e_df_effect",
                    "e_r2",
                    "v_r2",
                    "b_r2",
                    "ncp_type",
                    "rx",
                    "ry",
                    "ncp_type"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=500,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "e_es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "b_df_model",
                    "v_df_model",
                    "e_df_model",
                    "e_r2",
                    "v_r2",
                    "ncp_type",
                    "plot_log")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "e_es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "b_df_model",
                    "v_df_model",
                    "e_df_model",
                    "e_r2",
                    "v_r2",
                    "ncp_type",
                    "plot_log")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "e_es",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "b_df_model",
                    "v_df_model",
                    "e_df_model",
                    "e_r2",
                    "v_r2",
                    "ncp_type",
                    "plot_log")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="customnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="customtable",
                title="Power Analysis parameters",
                visible="(plot_to_table && !plot_x:none && !plot_y:none)",
                columns=list(
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number", 
                        `visible`=FALSE),
                    list(
                        `name`="n1", 
                        `title`="N\u2081", 
                        `type`="integer", 
                        `visible`=FALSE),
                    list(
                        `name`="n2", 
                        `title`="N\u2082", 
                        `type`="integer", 
                        `visible`=FALSE))))}))

pamlglmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlglm",
                version = c(0,0,1),
                options = options,
                results = pamlglmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' General Linear Model
#'
#' Something here
#' 
#' @param data the data as a data frame
#' @param aim .
#' @param mode .
#' @param b_es .
#' @param b_r2 .
#' @param b_df_model .
#' @param v_es .
#' @param v_df_model .
#' @param v_df_effect .
#' @param e_es .
#' @param e_df_model .
#' @param e_r2 .
#' @param e_df_effect .
#' @param power .
#' @param n .
#' @param sig.level .
#' @param alternative .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @param plot_log .
#' @param covs .
#' @param factors .
#' @param factors_list .
#' @param covs_order .
#' @param factors_order .
#' @param mixed_order .
#' @param eta .
#' @param eta_df_error .
#' @param epsilon .
#' @param omega .
#' @param gpower .
#' @param f2 .
#' @param use .
#' @param ncp_type .
#' @param rx a vector of strings naming the columns from \code{data}
#'   containing the correlations among independent variables
#' @param plot_x .
#' @param plot_y .
#' @param plot_custom_labels .
#' @param plot_z .
#' @param plot_x_from .
#' @param plot_x_to .
#' @param plot_z_lines .
#' @param plot_z_value .
#' @param plot_to_table .
#' @param explain .
#' @param .caller .
#' @param .interface .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$extrainfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effectsize} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$customnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$customtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlglm <- function(
    data,
    aim = "n",
    mode = "peta",
    b_es = 0.2,
    b_r2 = 0.05,
    b_df_model = 1,
    v_es = 0.2,
    v_df_model = 1,
    v_df_effect = 1,
    e_es = 0.2,
    e_df_model = 1,
    e_r2 = 0.2,
    e_df_effect = 1,
    power = 0.9,
    n = 20,
    sig.level = 0.05,
    alternative = "two.sided",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE,
    plot_log = FALSE,
    covs = 0,
    factors = 0,
    factors_list = list(
                list(var="factor 1", levels=0)),
    covs_order,
    factors_order,
    mixed_order,
    eta = 0.2,
    eta_df_error = 0,
    epsilon = 0,
    omega = 0,
    gpower = 0,
    f2 = 0,
    use = "none",
    ncp_type,
    rx = NULL,
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 0,
    plot_z_value = list(),
    plot_to_table = FALSE,
    explain = FALSE,
    .caller = "glm",
    .interface = "jamovi") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlglm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rx)) rx <- jmvcore::resolveQuo(jmvcore::enquo(rx))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rx), rx, NULL))


    options <- pamlglmOptions$new(
        aim = aim,
        mode = mode,
        b_es = b_es,
        b_r2 = b_r2,
        b_df_model = b_df_model,
        v_es = v_es,
        v_df_model = v_df_model,
        v_df_effect = v_df_effect,
        e_es = e_es,
        e_df_model = e_df_model,
        e_r2 = e_r2,
        e_df_effect = e_df_effect,
        power = power,
        n = n,
        sig.level = sig.level,
        alternative = alternative,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        covs = covs,
        factors = factors,
        factors_list = factors_list,
        covs_order = covs_order,
        factors_order = factors_order,
        mixed_order = mixed_order,
        eta = eta,
        eta_df_error = eta_df_error,
        epsilon = epsilon,
        omega = omega,
        gpower = gpower,
        f2 = f2,
        use = use,
        ncp_type = ncp_type,
        rx = rx,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        plot_to_table = plot_to_table,
        explain = explain,
        .caller = .caller,
        .interface = .interface)

    analysis <- pamlglmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

