
# This file is automatically generated, you probably don't want to edit this

pamljlmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamljlmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "lm",
            .interface = "jamovi",
            dep = NULL,
            factors = NULL,
            covs = NULL,
            model_terms = NULL,
            mute = FALSE,
            model_type = "lm",
            es = "etap",
            fixed_sizes = NULL,
            donotrun = FALSE, ...) {

            super$initialize(
                package="pamlj",
                name="pamljlm",
                requiresData=TRUE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="lm",
                hidden=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                permitted=list(
                    "factor",
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..model_terms <- jmvcore::OptionTerms$new(
                "model_terms",
                model_terms,
                default=NULL)
            private$..mute <- jmvcore::OptionBool$new(
                "mute",
                mute,
                default=FALSE)
            private$..model_type <- jmvcore::OptionList$new(
                "model_type",
                model_type,
                hidden=TRUE,
                options=list(
                    "lm"),
                default="lm")
            private$..es <- jmvcore::OptionList$new(
                "es",
                es,
                options=list(
                    "etap",
                    "beta",
                    "d"),
                default="etap")
            private$..fixed_sizes <- jmvcore::OptionArray$new(
                "fixed_sizes",
                fixed_sizes,
                template=jmvcore::OptionGroup$new(
                    "fixed_sizes",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionNumber$new(
                            "value",
                            NULL))))
            private$..donotrun <- jmvcore::OptionBool$new(
                "donotrun",
                donotrun,
                default=FALSE)

            self$.addOption(private$...caller)
            self$.addOption(private$...interface)
            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..model_terms)
            self$.addOption(private$..mute)
            self$.addOption(private$..model_type)
            self$.addOption(private$..es)
            self$.addOption(private$..fixed_sizes)
            self$.addOption(private$..donotrun)
        }),
    active = list(
        .caller = function() private$...caller$value,
        .interface = function() private$...interface$value,
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        model_terms = function() private$..model_terms$value,
        mute = function() private$..mute$value,
        model_type = function() private$..model_type$value,
        es = function() private$..es$value,
        fixed_sizes = function() private$..fixed_sizes$value,
        donotrun = function() private$..donotrun$value),
    private = list(
        ...caller = NA,
        ...interface = NA,
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..model_terms = NA,
        ..mute = NA,
        ..model_type = NA,
        ..es = NA,
        ..fixed_sizes = NA,
        ..donotrun = NA)
)

pamljlmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamljlmResults",
    inherit = jmvcore::Group,
    active = list(
        model = function() private$..model,
        info = function() private$.items[["info"]],
        anova = function() private$.items[["anova"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GLM Power Analysis")
            private$..model <- NULL
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Model Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="Info"),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`=""))))
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="ANOVA Omnibus tests",
                clearWith=list(
                    "dep",
                    "factors",
                    "covs",
                    "model_terms",
                    "fixed_sizes",
                    "mute"),
                columns=list(
                    list(
                        `name`="source", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="req. N", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="f2", 
                        `title`="f2", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="alpha", 
                        `title`="alpha", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="power", 
                        `title`="power", 
                        `type`="number", 
                        `format`="zto"))))},
        .setModel=function(x) private$..model <- x))

pamljlmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamljlmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamljlm",
                version = c(0,0,5),
                options = options,
                results = pamljlmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' GLM Power Analysis
#'
#' General Linear Model. Estimates models using \code{lm()} function and 
#' provides options to facilitate estimation of 
#' interactions, simple slopes, simple effects, post-hoc tests, contrast 
#' analysis, effect size indexes and visualization of the results.
#' 
#'
#' @examples
#' \dontrun{
#' data('ToothGrowth')
#' gamlj::gamljGlm(formula = len ~ supp,  data = ToothGrowth)
#'}
#' @param data the data as a data frame
#' @param .caller .
#' @param .interface .
#' @param dep a string naming the dependent variable from \code{data}; the
#'   variable must be numeric. Not needed if \code{formula} is used.
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}. Not needed if \code{formula} is used.
#' @param covs a vector of strings naming the covariates from \code{data}. Not
#'   needed if \code{formula} is used.
#' @param model_terms a list of character vectors describing fixed effects
#'   terms. Not needed if \code{formula} is used.
#' @param mute Not present in R
#' @param model_type .
#' @param es
#' @param fixed_sizes .
#' @param donotrun .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model} \tab \tab \tab \tab \tab a property \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a table of ANOVA results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
pamljlm <- function(
    data,
    .caller = "lm",
    .interface = "jamovi",
    dep = NULL,
    factors = NULL,
    covs = NULL,
    model_terms = NULL,
    mute = FALSE,
    model_type = "lm",
    es = "etap",
    fixed_sizes,
    donotrun = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamljlm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    if (inherits(model_terms, "formula")) model_terms <- jmvcore::decomposeFormula(model_terms)

    options <- pamljlmOptions$new(
        .caller = .caller,
        .interface = .interface,
        dep = dep,
        factors = factors,
        covs = covs,
        model_terms = model_terms,
        mute = mute,
        model_type = model_type,
        es = es,
        fixed_sizes = fixed_sizes,
        donotrun = donotrun)

    analysis <- pamljlmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

