
# This file is automatically generated, you probably don't want to edit this

pamlmixedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmixedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aim = "n",
            find = "k",
            code = "",
            fonts = "small",
            toggle = FALSE,
            run = NULL,
            sigma = 1,
            power = 0.9,
            sig.level = 0.05,
            mcR = 500,
            parallel = TRUE,
            set_seed = FALSE,
            seed = 42,
            .interface = "jamovi",
            .caller = "pamlmixed",
            clusterpars = list(),
            var_type = list(), ...) {

            super$initialize(
                package="pamlj",
                name="pamlmixed",
                requiresData=FALSE,
                ...)

            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power"))
            private$..find <- jmvcore::OptionList$new(
                "find",
                find,
                default="k",
                options=list(
                    "k",
                    "n"))
            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                hidden=TRUE,
                default="")
            private$..fonts <- jmvcore::OptionString$new(
                "fonts",
                fonts,
                default="small",
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)
            private$..run <- jmvcore::OptionAction$new(
                "run",
                run,
                hidden=TRUE)
            private$..sigma <- jmvcore::OptionNumber$new(
                "sigma",
                sigma,
                default=1)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..mcR <- jmvcore::OptionNumber$new(
                "mcR",
                mcR,
                default=500)
            private$..parallel <- jmvcore::OptionBool$new(
                "parallel",
                parallel,
                default=TRUE)
            private$..set_seed <- jmvcore::OptionBool$new(
                "set_seed",
                set_seed,
                default=FALSE)
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=42)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="pamlmixed",
                hidden=TRUE)
            private$..clusterpars <- jmvcore::OptionArray$new(
                "clusterpars",
                clusterpars,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "clusterpars",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionString$new(
                            "k",
                            NULL),
                        jmvcore::OptionString$new(
                            "n",
                            NULL))))
            private$..var_type <- jmvcore::OptionArray$new(
                "var_type",
                var_type,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "var_type",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "name",
                            NULL),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "categorical",
                                "continuous"),
                            default="continuous"),
                        jmvcore::OptionString$new(
                            "levels",
                            NULL))))

            self$.addOption(private$..aim)
            self$.addOption(private$..find)
            self$.addOption(private$..code)
            self$.addOption(private$..fonts)
            self$.addOption(private$..toggle)
            self$.addOption(private$..run)
            self$.addOption(private$..sigma)
            self$.addOption(private$..power)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..mcR)
            self$.addOption(private$..parallel)
            self$.addOption(private$..set_seed)
            self$.addOption(private$..seed)
            self$.addOption(private$...interface)
            self$.addOption(private$...caller)
            self$.addOption(private$..clusterpars)
            self$.addOption(private$..var_type)
        }),
    active = list(
        aim = function() private$..aim$value,
        find = function() private$..find$value,
        code = function() private$..code$value,
        fonts = function() private$..fonts$value,
        toggle = function() private$..toggle$value,
        run = function() private$..run$value,
        sigma = function() private$..sigma$value,
        power = function() private$..power$value,
        sig.level = function() private$..sig.level$value,
        mcR = function() private$..mcR$value,
        parallel = function() private$..parallel$value,
        set_seed = function() private$..set_seed$value,
        seed = function() private$..seed$value,
        .interface = function() private$...interface$value,
        .caller = function() private$...caller$value,
        clusterpars = function() private$..clusterpars$value,
        var_type = function() private$..var_type$value),
    private = list(
        ..aim = NA,
        ..find = NA,
        ..code = NA,
        ..fonts = NA,
        ..toggle = NA,
        ..run = NA,
        ..sigma = NA,
        ..power = NA,
        ..sig.level = NA,
        ..mcR = NA,
        ..parallel = NA,
        ..set_seed = NA,
        ..seed = NA,
        ...interface = NA,
        ...caller = NA,
        ..clusterpars = NA,
        ..var_type = NA)
)

pamlmixedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmixedResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        extrainfo = function() private$.items[["extrainfo"]],
        issues = function() private$.items[["issues"]],
        initnotes = function() private$.items[["initnotes"]],
        infotab = function() private$.items[["infotab"]],
        powertab = function() private$.items[["powertab"]],
        plotnotes = function() private$.items[["plotnotes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixed Models Power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="extrainfo",
                title="Extra Info",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="initnotes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="infotab",
                title="Model Information",
                columns=list(
                    list(
                        `name`="info", 
                        `title`="Info", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="value", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="specs", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="Estimate", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N per cluster", 
                        `type`="integer"),
                    list(
                        `name`="k", 
                        `title`="Cluster levels", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="df_error", 
                        `title`="df_error", 
                        `type`="number"),
                    list(
                        `name`="sig.level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="conv", 
                        `title`="% converged", 
                        `type`="number", 
                        `visible`="(method:mc)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))}))

pamlmixedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmixedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlmixed",
                version = c(0,5,0),
                options = options,
                results = pamlmixedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Linear Mixed Models
#'
#' Something here
#' 
#' @param aim The aim of the analysis: \code{n} (default) for sample size,
#'   \code{power} to estimate power
#' @param find The aim of the analysis: \code{n} (default) for sample size,
#'   \code{power} to estimate power
#' @param code .
#' @param fonts .
#' @param toggle .
#' @param run .
#' @param sigma Residual variance
#' @param power Minimal desired power
#' @param sig.level Type I error rate (significance cut-off or alpha)
#' @param mcR Number of repetitions for Monte Carlo method
#' @param parallel Logical: should parallel computing be used for the Monte
#'   Carlo method
#' @param set_seed not used in R
#' @param seed not used in R
#' @param .interface Used for internal purposes
#' @param .caller Used for internal purposes
#' @param clusterpars .
#' @param var_type .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$extrainfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$initnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infotab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$infotab$asDF}
#'
#' \code{as.data.frame(results$infotab)}
#'
#' @export
pamlmixed <- function(
    aim = "n",
    find = "k",
    code = "",
    fonts = "small",
    toggle = FALSE,
    run,
    sigma = 1,
    power = 0.9,
    sig.level = 0.05,
    mcR = 500,
    parallel = TRUE,
    set_seed = FALSE,
    seed = 42,
    .interface = "jamovi",
    .caller = "pamlmixed",
    clusterpars = list(),
    var_type = list()) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlmixed requires jmvcore to be installed (restart may be required)")


    options <- pamlmixedOptions$new(
        aim = aim,
        find = find,
        code = code,
        fonts = fonts,
        toggle = toggle,
        run = run,
        sigma = sigma,
        power = power,
        sig.level = sig.level,
        mcR = mcR,
        parallel = parallel,
        set_seed = set_seed,
        seed = seed,
        .interface = .interface,
        .caller = .caller,
        clusterpars = clusterpars,
        var_type = var_type)

    analysis <- pamlmixedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

