# This file is automatically generated, you probably don't want to edit this

pamlcorrOptions <- if (requireNamespace("jmvcore", quietly = TRUE)) {
    R6::R6Class(
        "pamlcorrOptions",
        inherit = jmvcore::Options,
        public = list(
            initialize = function(aim = "n",
                                  es = 0.5,
                                  power = 0.9,
                                  n = 20,
                                  sig.level = 0.05,
                                  alternative = "two.sided",
                                  plot_contour = FALSE,
                                  plot_escurve = FALSE,
                                  plot_ncurve = FALSE,
                                  plot_log = TRUE,
                                  plot_palette = "viridis",
                                  plot_x = "none",
                                  plot_y = "none",
                                  plot_custom_labels = FALSE,
                                  plot_z = "none",
                                  plot_x_from = 0,
                                  plot_x_to = 0,
                                  plot_z_lines = 1,
                                  plot_z_value = list(),
                                  plot_to_table = FALSE,
                                  .interface = "jamovi",
                                  .caller = "correlation", ...) {
                super$initialize(
                    package = "pamlj",
                    name = "pamlcorr",
                    requiresData = FALSE,
                    ...
                )

                private$..aim <- jmvcore::OptionList$new(
                    "aim",
                    aim,
                    default = "n",
                    options = list(
                        "n",
                        "power",
                        "es"
                    )
                )
                private$..es <- jmvcore::OptionNumber$new(
                    "es",
                    es,
                    default = 0.5
                )
                private$..power <- jmvcore::OptionNumber$new(
                    "power",
                    power,
                    default = 0.9
                )
                private$..n <- jmvcore::OptionNumber$new(
                    "n",
                    n,
                    default = 20
                )
                private$..sig.level <- jmvcore::OptionNumber$new(
                    "sig.level",
                    sig.level,
                    default = 0.05
                )
                private$..alternative <- jmvcore::OptionList$new(
                    "alternative",
                    alternative,
                    default = "two.sided",
                    options = list(
                        "two.sided",
                        "one.sided"
                    )
                )
                private$..plot_contour <- jmvcore::OptionBool$new(
                    "plot_contour",
                    plot_contour,
                    default = FALSE
                )
                private$..plot_escurve <- jmvcore::OptionBool$new(
                    "plot_escurve",
                    plot_escurve,
                    default = FALSE
                )
                private$..plot_ncurve <- jmvcore::OptionBool$new(
                    "plot_ncurve",
                    plot_ncurve,
                    default = FALSE
                )
                private$..plot_log <- jmvcore::OptionBool$new(
                    "plot_log",
                    plot_log,
                    default = TRUE
                )
                private$..plot_palette <- jmvcore::OptionList$new(
                    "plot_palette",
                    plot_palette,
                    default = "viridis",
                    options = list(
                        "viridis",
                        "rocket",
                        "mako",
                        "cividis",
                        "plasma",
                        "turbo",
                        "husky"
                    )
                )
                private$..plot_x <- jmvcore::OptionList$new(
                    "plot_x",
                    plot_x,
                    default = "none",
                    options = list(
                        "none",
                        "n",
                        "power",
                        "es"
                    )
                )
                private$..plot_y <- jmvcore::OptionList$new(
                    "plot_y",
                    plot_y,
                    default = "none",
                    options = list(
                        "none",
                        "n",
                        "power",
                        "es"
                    )
                )
                private$..plot_custom_labels <- jmvcore::OptionBool$new(
                    "plot_custom_labels",
                    plot_custom_labels,
                    default = FALSE
                )
                private$..plot_z <- jmvcore::OptionList$new(
                    "plot_z",
                    plot_z,
                    default = "none",
                    options = list(
                        "none",
                        "n",
                        "power",
                        "es",
                        "sig.level"
                    )
                )
                private$..plot_x_from <- jmvcore::OptionNumber$new(
                    "plot_x_from",
                    plot_x_from,
                    default = 0
                )
                private$..plot_x_to <- jmvcore::OptionNumber$new(
                    "plot_x_to",
                    plot_x_to,
                    default = 0
                )
                private$..plot_z_lines <- jmvcore::OptionNumber$new(
                    "plot_z_lines",
                    plot_z_lines,
                    default = 1,
                    min = 1
                )
                private$..plot_z_value <- jmvcore::OptionArray$new(
                    "plot_z_value",
                    plot_z_value,
                    default = list(),
                    template = jmvcore::OptionString$new(
                        "plot_z_value",
                        NULL
                    )
                )
                private$..plot_to_table <- jmvcore::OptionBool$new(
                    "plot_to_table",
                    plot_to_table,
                    default = FALSE
                )
                private$...interface <- jmvcore::OptionString$new(
                    ".interface",
                    .interface,
                    default = "jamovi",
                    hidden = TRUE
                )
                private$...caller <- jmvcore::OptionString$new(
                    ".caller",
                    .caller,
                    default = "correlation",
                    hidden = TRUE
                )

                self$.addOption(private$..aim)
                self$.addOption(private$..es)
                self$.addOption(private$..power)
                self$.addOption(private$..n)
                self$.addOption(private$..sig.level)
                self$.addOption(private$..alternative)
                self$.addOption(private$..plot_contour)
                self$.addOption(private$..plot_escurve)
                self$.addOption(private$..plot_ncurve)
                self$.addOption(private$..plot_log)
                self$.addOption(private$..plot_palette)
                self$.addOption(private$..plot_x)
                self$.addOption(private$..plot_y)
                self$.addOption(private$..plot_custom_labels)
                self$.addOption(private$..plot_z)
                self$.addOption(private$..plot_x_from)
                self$.addOption(private$..plot_x_to)
                self$.addOption(private$..plot_z_lines)
                self$.addOption(private$..plot_z_value)
                self$.addOption(private$..plot_to_table)
                self$.addOption(private$...interface)
                self$.addOption(private$...caller)
            }
        ),
        active = list(
            aim = function() private$..aim$value,
            es = function() private$..es$value,
            power = function() private$..power$value,
            n = function() private$..n$value,
            sig.level = function() private$..sig.level$value,
            alternative = function() private$..alternative$value,
            plot_contour = function() private$..plot_contour$value,
            plot_escurve = function() private$..plot_escurve$value,
            plot_ncurve = function() private$..plot_ncurve$value,
            plot_log = function() private$..plot_log$value,
            plot_palette = function() private$..plot_palette$value,
            plot_x = function() private$..plot_x$value,
            plot_y = function() private$..plot_y$value,
            plot_custom_labels = function() private$..plot_custom_labels$value,
            plot_z = function() private$..plot_z$value,
            plot_x_from = function() private$..plot_x_from$value,
            plot_x_to = function() private$..plot_x_to$value,
            plot_z_lines = function() private$..plot_z_lines$value,
            plot_z_value = function() private$..plot_z_value$value,
            plot_to_table = function() private$..plot_to_table$value,
            .interface = function() private$...interface$value,
            .caller = function() private$...caller$value
        ),
        private = list(
            ..aim = NA,
            ..es = NA,
            ..power = NA,
            ..n = NA,
            ..sig.level = NA,
            ..alternative = NA,
            ..plot_contour = NA,
            ..plot_escurve = NA,
            ..plot_ncurve = NA,
            ..plot_log = NA,
            ..plot_palette = NA,
            ..plot_x = NA,
            ..plot_y = NA,
            ..plot_custom_labels = NA,
            ..plot_z = NA,
            ..plot_x_from = NA,
            ..plot_x_to = NA,
            ..plot_z_lines = NA,
            ..plot_z_value = NA,
            ..plot_to_table = NA,
            ...interface = NA,
            ...caller = NA
        )
    )
}

pamlcorrResults <- if (requireNamespace("jmvcore", quietly = TRUE)) {
    R6::R6Class(
        "pamlcorrResults",
        inherit = jmvcore::Group,
        active = list(
            intro = function() private$.items[["intro"]],
            extrainfo = function() private$.items[["extrainfo"]],
            issues = function() private$.items[["issues"]],
            powertab = function() private$.items[["powertab"]],
            powerbyes = function() private$.items[["powerbyes"]],
            plotnotes = function() private$.items[["plotnotes"]],
            powerContour = function() private$.items[["powerContour"]],
            powerEscurve = function() private$.items[["powerEscurve"]],
            powerNcurve = function() private$.items[["powerNcurve"]],
            powerCustom = function() private$.items[["powerCustom"]],
            customnotes = function() private$.items[["customnotes"]],
            customtable = function() private$.items[["customtable"]]
        ),
        private = list(),
        public = list(
            initialize = function(options) {
                super$initialize(
                    options = options,
                    name = "",
                    title = "Correlation power analysis"
                )
                self$add(jmvcore::Html$new(
                    options = options,
                    name = "intro",
                    title = "Introduction"
                ))
                self$add(jmvcore::Html$new(
                    options = options,
                    name = "extrainfo",
                    title = "Extra Info",
                    visible = FALSE
                ))
                self$add(jmvcore::Html$new(
                    options = options,
                    name = "issues",
                    title = "Issues",
                    visible = FALSE
                ))
                self$add(jmvcore::Table$new(
                    options = options,
                    name = "powertab",
                    title = "A Priori Power Analysis",
                    rows = 1,
                    refs = list(
                        "pamlj"
                    ),
                    clearWith = list(
                        "es",
                        "power",
                        "n",
                        "sig.level",
                        "aim",
                        "alternative"
                    ),
                    columns = list(
                        list(
                            `name` = "n",
                            `title` = "N",
                            `type` = "integer"
                        ),
                        list(
                            `name` = "es",
                            `title` = "Effect size",
                            `type` = "number"
                        ),
                        list(
                            `name` = "power",
                            `title` = "Power",
                            `type` = "number"
                        ),
                        list(
                            `name` = "sig.level",
                            `title` = "\u03B1",
                            `type` = "number"
                        )
                    )
                ))
                self$add(jmvcore::Table$new(
                    options = options,
                    name = "powerbyes",
                    title = "Power by Effect Size",
                    rows = 4,
                    clearWith = list(
                        "es",
                        "power",
                        "n",
                        "sig.level",
                        "aim",
                        "alternative"
                    ),
                    columns = list(
                        list(
                            `name` = "es",
                            `title` = "True effect size",
                            `type` = "number"
                        ),
                        list(
                            `name` = "power",
                            `title` = "Power to detect",
                            `type` = "text"
                        ),
                        list(
                            `name` = "desc",
                            `title` = "Description",
                            `type` = "text"
                        )
                    )
                ))
                self$add(jmvcore::Html$new(
                    options = options,
                    name = "plotnotes",
                    title = "Plot notes",
                    visible = FALSE
                ))
                self$add(jmvcore::Image$new(
                    options = options,
                    name = "powerContour",
                    title = "Power Contour",
                    width = 500,
                    height = 350,
                    renderFun = ".plot_contour",
                    visible = "(plot_contour)"
                ))
                self$add(jmvcore::Image$new(
                    options = options,
                    name = "powerEscurve",
                    title = "Power Curve by Effect Size",
                    width = 400,
                    height = 350,
                    renderFun = ".plot_escurve",
                    visible = "(plot_escurve)"
                ))
                self$add(jmvcore::Image$new(
                    options = options,
                    name = "powerNcurve",
                    title = "Power Curve by N",
                    width = 400,
                    height = 350,
                    renderFun = ".plot_ncurve",
                    visible = "(plot_ncurve)"
                ))
                self$add(jmvcore::Image$new(
                    options = options,
                    name = "powerCustom",
                    title = "Power Parameters",
                    width = 450,
                    height = 350,
                    renderFun = ".plot_custom",
                    visible = FALSE
                ))
                self$add(jmvcore::Html$new(
                    options = options,
                    name = "customnotes",
                    title = "Plot notes",
                    visible = FALSE
                ))
                self$add(jmvcore::Table$new(
                    options = options,
                    name = "customtable",
                    title = "Power Analysis parameters",
                    visible = "(plot_to_table && !plot_x:none && !plot_y:none)",
                    columns = list(
                        list(
                            `name` = "y",
                            `title` = "Y",
                            `type` = "number"
                        ),
                        list(
                            `name` = "x",
                            `title` = "X",
                            `type` = "number"
                        ),
                        list(
                            `name` = "z",
                            `title` = "Z",
                            `type` = "number",
                            `visible` = FALSE
                        )
                    )
                ))
            }
        )
    )
}

pamlcorrBase <- if (requireNamespace("jmvcore", quietly = TRUE)) {
    R6::R6Class(
        "pamlcorrBase",
        inherit = jmvcore::Analysis,
        public = list(
            initialize = function(options, data = NULL, datasetId = "", analysisId = "", revision = 0) {
                super$initialize(
                    package = "pamlj",
                    name = "pamlcorr",
                    version = c(0, 5, 0),
                    options = options,
                    results = pamlcorrResults$new(options = options),
                    data = data,
                    datasetId = datasetId,
                    analysisId = analysisId,
                    revision = revision,
                    pause = NULL,
                    completeWhenFilled = FALSE,
                    requiresMissings = FALSE,
                    weightsSupport = "na"
                )
            }
        )
    )
}

#' Correlation
#'
#' Something here
#'
#' @param aim The aim of the analysis: \code{n} (default) for sample size,
#'   \code{power} to estimate power, \code{es} for effect size (correlation)
#' @param es The expected effect size, i.e. the expected correlation
#' @param power Minimal desired power
#' @param n Sample size
#' @param sig.level Type I error rate (significance cut-off or alpha)
#' @param alternative .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @param plot_log .
#' @param plot_palette .
#' @param plot_x Parameter in the X-axis of custom power parameters plot.
#'   \code{n}, \code{power} or \code{es}, the latest being the effect size.
#' @param plot_y Parameter in the Y-axis of custom power parameters plot.
#'   \code{n}, \code{power} or \code{es}, the latest being the effect size.
#' @param plot_custom_labels Add value labels to the custom power parameters
#'   plot, default FALSE.
#' @param plot_z break down the custom power parameters plot by a parameter.
#'   \code{n}, \code{power}, \code{sig.level} or \code{es} for effect size
#' @param plot_x_from Range for the parameter in the X-axis of custom power
#'   parameters plot. Starting value.
#' @param plot_x_to Range for the parameter in the X-axis of custom power
#'   parameters plot. Ending value.
#' @param plot_z_lines not used in R
#' @param plot_z_value Values of the parameter to break the plot by
#' @param plot_to_table Produce a table of the values plotted in custom power
#'   parameters plot
#' @param .interface Used for internal purposes
#' @param .caller Used for internal purposes
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$extrainfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$customnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$customtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlcorr <- function(
    aim = "n",
    es = 0.5,
    power = 0.9,
    n = 20,
    sig.level = 0.05,
    alternative = "two.sided",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE,
    plot_log = TRUE,
    plot_palette = "viridis",
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 1,
    plot_z_value = list(),
    plot_to_table = FALSE,
    .interface = "jamovi",
    .caller = "correlation") {
    if (!requireNamespace("jmvcore", quietly = TRUE)) {
        stop("pamlcorr requires jmvcore to be installed (restart may be required)")
    }


    options <- pamlcorrOptions$new(
        aim = aim,
        es = es,
        power = power,
        n = n,
        sig.level = sig.level,
        alternative = alternative,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        plot_palette = plot_palette,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        plot_to_table = plot_to_table,
        .interface = .interface,
        .caller = .caller
    )

    analysis <- pamlcorrClass$new(
        options = options,
        data = data
    )

    analysis$run()

    analysis$results
}
