
# This file is automatically generated, you probably don't want to edit this

pamlsemOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlsemOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aim = "n",
            code = "",
            fonts = "small",
            toggle = FALSE,
            power = 0.9,
            n = 100,
            sig.level = 0.05,
            alternative = "two.sided",
            estimator = "ML",
            standardized = TRUE,
            method = "analytic",
            mc_test = "lrt",
            mcR = 500,
            parallel = TRUE,
            set_seed = FALSE,
            seed = 42,
            table_pwbyn = TRUE,
            plot_ncurve = FALSE,
            plot_log = FALSE,
            plot_palette = "viridis",
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 1,
            plot_z_value = list(),
            plot_to_table = FALSE,
            explain = FALSE,
            lav_diagram = TRUE,
            .interface = "jamovi",
            .caller = "pamlsem", ...) {

            super$initialize(
                package="pamlj",
                name="pamlsem",
                requiresData=FALSE,
                ...)

            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power"))
            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                hidden=TRUE,
                default="")
            private$..fonts <- jmvcore::OptionString$new(
                "fonts",
                fonts,
                default="small",
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=100)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                default="two.sided",
                options=list(
                    "two.sided",
                    "one.sided"))
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                default="ML",
                options=list(
                    "ML",
                    "WLS",
                    "DWLS",
                    "ULS"))
            private$..standardized <- jmvcore::OptionBool$new(
                "standardized",
                standardized,
                default=TRUE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                default="analytic",
                options=list(
                    "analytic",
                    "mc"))
            private$..mc_test <- jmvcore::OptionList$new(
                "mc_test",
                mc_test,
                default="lrt",
                options=list(
                    "lrt",
                    "score"))
            private$..mcR <- jmvcore::OptionNumber$new(
                "mcR",
                mcR,
                default=500)
            private$..parallel <- jmvcore::OptionBool$new(
                "parallel",
                parallel,
                default=TRUE)
            private$..set_seed <- jmvcore::OptionBool$new(
                "set_seed",
                set_seed,
                default=FALSE)
            private$..seed <- jmvcore::OptionNumber$new(
                "seed",
                seed,
                default=42)
            private$..table_pwbyn <- jmvcore::OptionBool$new(
                "table_pwbyn",
                table_pwbyn,
                default=TRUE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=FALSE)
            private$..plot_palette <- jmvcore::OptionList$new(
                "plot_palette",
                plot_palette,
                default="viridis",
                options=list(
                    "viridis",
                    "rocket",
                    "mako",
                    "cividis",
                    "plasma",
                    "turbo",
                    "husky"))
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "sig.level"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=1,
                min=1)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..plot_to_table <- jmvcore::OptionBool$new(
                "plot_to_table",
                plot_to_table,
                default=FALSE)
            private$..explain <- jmvcore::OptionBool$new(
                "explain",
                explain,
                default=FALSE)
            private$..lav_diagram <- jmvcore::OptionBool$new(
                "lav_diagram",
                lav_diagram,
                default=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="pamlsem",
                hidden=TRUE)

            self$.addOption(private$..aim)
            self$.addOption(private$..code)
            self$.addOption(private$..fonts)
            self$.addOption(private$..toggle)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..alternative)
            self$.addOption(private$..estimator)
            self$.addOption(private$..standardized)
            self$.addOption(private$..method)
            self$.addOption(private$..mc_test)
            self$.addOption(private$..mcR)
            self$.addOption(private$..parallel)
            self$.addOption(private$..set_seed)
            self$.addOption(private$..seed)
            self$.addOption(private$..table_pwbyn)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..plot_palette)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..plot_to_table)
            self$.addOption(private$..explain)
            self$.addOption(private$..lav_diagram)
            self$.addOption(private$...interface)
            self$.addOption(private$...caller)
        }),
    active = list(
        aim = function() private$..aim$value,
        code = function() private$..code$value,
        fonts = function() private$..fonts$value,
        toggle = function() private$..toggle$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        sig.level = function() private$..sig.level$value,
        alternative = function() private$..alternative$value,
        estimator = function() private$..estimator$value,
        standardized = function() private$..standardized$value,
        method = function() private$..method$value,
        mc_test = function() private$..mc_test$value,
        mcR = function() private$..mcR$value,
        parallel = function() private$..parallel$value,
        set_seed = function() private$..set_seed$value,
        seed = function() private$..seed$value,
        table_pwbyn = function() private$..table_pwbyn$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        plot_palette = function() private$..plot_palette$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        plot_to_table = function() private$..plot_to_table$value,
        explain = function() private$..explain$value,
        lav_diagram = function() private$..lav_diagram$value,
        .interface = function() private$...interface$value,
        .caller = function() private$...caller$value),
    private = list(
        ..aim = NA,
        ..code = NA,
        ..fonts = NA,
        ..toggle = NA,
        ..power = NA,
        ..n = NA,
        ..sig.level = NA,
        ..alternative = NA,
        ..estimator = NA,
        ..standardized = NA,
        ..method = NA,
        ..mc_test = NA,
        ..mcR = NA,
        ..parallel = NA,
        ..set_seed = NA,
        ..seed = NA,
        ..table_pwbyn = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..plot_palette = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..plot_to_table = NA,
        ..explain = NA,
        ..lav_diagram = NA,
        ...interface = NA,
        ...caller = NA)
)

pamlsemResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlsemResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        extrainfo = function() private$.items[["extrainfo"]],
        issues = function() private$.items[["issues"]],
        initnotes = function() private$.items[["initnotes"]],
        diagram = function() private$.items[["diagram"]],
        powertab = function() private$.items[["powertab"]],
        powerbyn = function() private$.items[["powerbyn"]],
        plotnotes = function() private$.items[["plotnotes"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        powerCustom = function() private$.items[["powerCustom"]],
        customnotes = function() private$.items[["customnotes"]],
        customtable = function() private$.items[["customtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SEM Power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="extrainfo",
                title="Extra Info",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="initnotes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="diagram",
                title="",
                width=500,
                height=400,
                renderFun=".plot_diagram",
                visible="(lav_diagram)",
                clearWith=list(
                    "code"),
                refs=list(
                    "semplot")))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                refs=list(
                    "sempower",
                    "lavaan",
                    "pamlj"),
                clearWith=list(
                    "aim",
                    "code",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "mcR",
                    "parallel",
                    "seed",
                    "set_seed",
                    "method",
                    "estimator",
                    "standardize",
                    "mc_test",
                    "mcR",
                    "parallel",
                    "set_seed",
                    "seed"),
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="model", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="es", 
                        `title`="RMSEA", 
                        `type`="number"),
                    list(
                        `name`="test", 
                        `title`="Chi-squared", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="sig.level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="conv", 
                        `title`="% converged", 
                        `type`="number", 
                        `visible`="(method:mc)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyn",
                title="Power by Sample size",
                rows=4,
                visible="(table_pwbyn)",
                clearWith=list(
                    "code",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "seed",
                    "set_seed",
                    "method",
                    "estimator",
                    "standardize"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="Sample size", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="customnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="customtable",
                title="Power Analysis parameters",
                visible="(plot_to_table && !plot_x:none && !plot_y:none)",
                columns=list(
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number", 
                        `visible`=FALSE),
                    list(
                        `name`="es", 
                        `title`="ME", 
                        `type`="Number"))))}))

pamlsemBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlsemBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlsem",
                version = c(0,5,0),
                options = options,
                results = pamlsemResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Structural Equations Models
#'
#' Something here
#' 
#' @param aim The aim of the analysis: \code{n} (default) for sample size,
#'   \code{power} to estimate power
#' @param code .
#' @param fonts .
#' @param toggle .
#' @param power Minimal desired power
#' @param n Sample size
#' @param sig.level Type I error rate (significance cut-off or alpha)
#' @param alternative Two-tailed vs one-tailed test
#' @param estimator Estimator method used in SEM. \code{ML} for Maximum
#'   Likelihood
#' @param standardized Assume the observed variables are standardized (TRUE)
#'   or not (FALSE)
#' @param method Use analytic methods for computation of power parameter
#'   (\code{analytic}) or Monte Carlo (\code{mc})
#' @param mc_test which test is used in Monte Carlo simulations: \code{lrt}
#'   for LRT or \code{score} for the Score test.
#' @param mcR Number of repetitions for Monte Carlo method
#' @param parallel Logical: should parallel computing be used for the Monte
#'   Carlo method
#' @param set_seed not used in R
#' @param seed not used in R
#' @param table_pwbyn .
#' @param plot_ncurve .
#' @param plot_log .
#' @param plot_palette .
#' @param plot_x .
#' @param plot_y .
#' @param plot_custom_labels .
#' @param plot_z .
#' @param plot_x_from .
#' @param plot_x_to .
#' @param plot_z_lines .
#' @param plot_z_value .
#' @param plot_to_table .
#' @param explain not used in R
#' @param lav_diagram Output the path diagram corresponding to the input model
#' @param .interface Used for internal purposes
#' @param .caller Used for internal purposes
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$extrainfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$initnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$diagram} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyn} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$customnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$customtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlsem <- function(
    aim = "n",
    code = "",
    fonts = "small",
    toggle = FALSE,
    power = 0.9,
    n = 100,
    sig.level = 0.05,
    alternative = "two.sided",
    estimator = "ML",
    standardized = TRUE,
    method = "analytic",
    mc_test = "lrt",
    mcR = 500,
    parallel = TRUE,
    set_seed = FALSE,
    seed = 42,
    table_pwbyn = TRUE,
    plot_ncurve = FALSE,
    plot_log = FALSE,
    plot_palette = "viridis",
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 1,
    plot_z_value = list(),
    plot_to_table = FALSE,
    explain = FALSE,
    lav_diagram = TRUE,
    .interface = "jamovi",
    .caller = "pamlsem") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlsem requires jmvcore to be installed (restart may be required)")


    options <- pamlsemOptions$new(
        aim = aim,
        code = code,
        fonts = fonts,
        toggle = toggle,
        power = power,
        n = n,
        sig.level = sig.level,
        alternative = alternative,
        estimator = estimator,
        standardized = standardized,
        method = method,
        mc_test = mc_test,
        mcR = mcR,
        parallel = parallel,
        set_seed = set_seed,
        seed = seed,
        table_pwbyn = table_pwbyn,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        plot_palette = plot_palette,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        plot_to_table = plot_to_table,
        explain = explain,
        lav_diagram = lav_diagram,
        .interface = .interface,
        .caller = .caller)

    analysis <- pamlsemClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

