
# This file is automatically generated, you probably don't want to edit this

pamlttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "ttest",
            aim = "n",
            mode = "ttestind",
            ttestind_es = 0.2,
            ttestind_n = 20,
            ttestind_nratio = 1,
            ttestpaired_es = 0.2,
            ttestpaired_n = 20,
            ttestone_es = 0.2,
            ttestone_n = 20,
            power = 0.9,
            sample = 20,
            alpha = 0.05,
            tails = "two",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE, ...) {

            super$initialize(
                package="pamlj",
                name="pamlttest",
                requiresData=FALSE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="ttest",
                hidden=TRUE)
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "ttestind",
                    "ttestpaired",
                    "ttestone"),
                default="ttestind")
            private$..ttestind_es <- jmvcore::OptionNumber$new(
                "ttestind_es",
                ttestind_es,
                default=0.2)
            private$..ttestind_n <- jmvcore::OptionNumber$new(
                "ttestind_n",
                ttestind_n,
                default=20)
            private$..ttestind_nratio <- jmvcore::OptionNumber$new(
                "ttestind_nratio",
                ttestind_nratio,
                default=1)
            private$..ttestpaired_es <- jmvcore::OptionNumber$new(
                "ttestpaired_es",
                ttestpaired_es,
                default=0.2)
            private$..ttestpaired_n <- jmvcore::OptionNumber$new(
                "ttestpaired_n",
                ttestpaired_n,
                default=20)
            private$..ttestone_es <- jmvcore::OptionNumber$new(
                "ttestone_es",
                ttestone_es,
                default=0.2)
            private$..ttestone_n <- jmvcore::OptionNumber$new(
                "ttestone_n",
                ttestone_n,
                default=20)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sample <- jmvcore::OptionNumber$new(
                "sample",
                sample,
                default=20)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..tails <- jmvcore::OptionList$new(
                "tails",
                tails,
                default="two",
                options=list(
                    "two",
                    "one"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)

            self$.addOption(private$...caller)
            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..ttestind_es)
            self$.addOption(private$..ttestind_n)
            self$.addOption(private$..ttestind_nratio)
            self$.addOption(private$..ttestpaired_es)
            self$.addOption(private$..ttestpaired_n)
            self$.addOption(private$..ttestone_es)
            self$.addOption(private$..ttestone_n)
            self$.addOption(private$..power)
            self$.addOption(private$..sample)
            self$.addOption(private$..alpha)
            self$.addOption(private$..tails)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
        }),
    active = list(
        .caller = function() private$...caller$value,
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        ttestind_es = function() private$..ttestind_es$value,
        ttestind_n = function() private$..ttestind_n$value,
        ttestind_nratio = function() private$..ttestind_nratio$value,
        ttestpaired_es = function() private$..ttestpaired_es$value,
        ttestpaired_n = function() private$..ttestpaired_n$value,
        ttestone_es = function() private$..ttestone_es$value,
        ttestone_n = function() private$..ttestone_n$value,
        power = function() private$..power$value,
        sample = function() private$..sample$value,
        alpha = function() private$..alpha$value,
        tails = function() private$..tails$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value),
    private = list(
        ...caller = NA,
        ..aim = NA,
        ..mode = NA,
        ..ttestind_es = NA,
        ..ttestind_n = NA,
        ..ttestind_nratio = NA,
        ..ttestpaired_es = NA,
        ..ttestpaired_n = NA,
        ..ttestone_es = NA,
        ..ttestone_n = NA,
        ..power = NA,
        ..sample = NA,
        ..alpha = NA,
        ..tails = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA)
)

pamlttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlttestResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GLM power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                refs="pwr",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="aes", 
                        `title`="f\u00B2", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="df(res)", 
                        `type`="integer"),
                    list(
                        `name`="alpha", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !aim:n)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !aim:es)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2")))}))

pamlttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlttest",
                version = c(0,0,1),
                options = options,
                results = pamlttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' T-Test
#'
#' Something here
#' 
#' @param .caller .
#' @param aim .
#' @param mode .
#' @param ttestind_es .
#' @param ttestind_n .
#' @param ttestind_nratio .
#' @param ttestpaired_es .
#' @param ttestpaired_n .
#' @param ttestone_es .
#' @param ttestone_n .
#' @param power .
#' @param sample .
#' @param alpha .
#' @param tails .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlttest <- function(
    .caller = "ttest",
    aim = "n",
    mode = "ttestind",
    ttestind_es = 0.2,
    ttestind_n = 20,
    ttestind_nratio = 1,
    ttestpaired_es = 0.2,
    ttestpaired_n = 20,
    ttestone_es = 0.2,
    ttestone_n = 20,
    power = 0.9,
    sample = 20,
    alpha = 0.05,
    tails = "two",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlttest requires jmvcore to be installed (restart may be required)")


    options <- pamlttestOptions$new(
        .caller = .caller,
        aim = aim,
        mode = mode,
        ttestind_es = ttestind_es,
        ttestind_n = ttestind_n,
        ttestind_nratio = ttestind_nratio,
        ttestpaired_es = ttestpaired_es,
        ttestpaired_n = ttestpaired_n,
        ttestone_es = ttestone_es,
        ttestone_n = ttestone_n,
        power = power,
        sample = sample,
        alpha = alpha,
        tails = tails,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve)

    analysis <- pamlttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

