
# This file is automatically generated, you probably don't want to edit this

pamlglmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "glmbeta",
            aim = "n",
            es = 0.2,
            r2 = 0.04,
            df_model = 1,
            power_r2 = NULL,
            power = 0.9,
            sample = 20,
            alpha = 0.05,
            tails = "two",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE, ...) {

            super$initialize(
                package="pamlj",
                name="pamlglm",
                requiresData=FALSE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="glmbeta",
                hidden=TRUE)
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..es <- jmvcore::OptionNumber$new(
                "es",
                es,
                default=0.2)
            private$..r2 <- jmvcore::OptionNumber$new(
                "r2",
                r2,
                default=0.04)
            private$..df_model <- jmvcore::OptionNumber$new(
                "df_model",
                df_model,
                default=1)
            private$..power_r2 <- jmvcore::OptionBool$new(
                "power_r2",
                power_r2)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sample <- jmvcore::OptionNumber$new(
                "sample",
                sample,
                default=20)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..tails <- jmvcore::OptionList$new(
                "tails",
                tails,
                default="two",
                options=list(
                    "two",
                    "one"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)

            self$.addOption(private$...caller)
            self$.addOption(private$..aim)
            self$.addOption(private$..es)
            self$.addOption(private$..r2)
            self$.addOption(private$..df_model)
            self$.addOption(private$..power_r2)
            self$.addOption(private$..power)
            self$.addOption(private$..sample)
            self$.addOption(private$..alpha)
            self$.addOption(private$..tails)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
        }),
    active = list(
        .caller = function() private$...caller$value,
        aim = function() private$..aim$value,
        es = function() private$..es$value,
        r2 = function() private$..r2$value,
        df_model = function() private$..df_model$value,
        power_r2 = function() private$..power_r2$value,
        power = function() private$..power$value,
        sample = function() private$..sample$value,
        alpha = function() private$..alpha$value,
        tails = function() private$..tails$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value),
    private = list(
        ...caller = NA,
        ..aim = NA,
        ..es = NA,
        ..r2 = NA,
        ..df_model = NA,
        ..power_r2 = NA,
        ..power = NA,
        ..sample = NA,
        ..alpha = NA,
        ..tails = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA)
)

pamlglmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        powerr2 = function() private$.items[["powerr2"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GLM power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "df_model",
                    "r2"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="es", 
                        `title`="\u03B2", 
                        `type`="number"),
                    list(
                        `name`="aes", 
                        `title`="f\u00B2", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="df(res)", 
                        `type`="integer"),
                    list(
                        `name`="alpha", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "df_model",
                    "r2"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    powertab = function() private$.items[["powertab"]],
                    powerbyes = function() private$.items[["powerbyes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="powerr2",
                            title="Full Model Power")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="powertab",
                            title="A Priori Power Analysis",
                            visible=FALSE,
                            rows=1,
                            clearWith=list(
                                "es",
                                "power",
                                "sample",
                                "alpha",
                                "aim",
                                "tails",
                                "df_model",
                                "r2",
                                "power_r2"),
                            columns=list(
                                list(
                                    `name`="n", 
                                    `title`="N", 
                                    `type`="integer"),
                                list(
                                    `name`="r2", 
                                    `title`="R\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="power", 
                                    `title`="Power", 
                                    `type`="number"),
                                list(
                                    `name`="df1", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="df2", 
                                    `title`="df(res)", 
                                    `type`="integer"),
                                list(
                                    `name`="alpha", 
                                    `title`="&alpha;", 
                                    `type`="number"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="powerbyes",
                            title="Power by Effect Size",
                            rows=4,
                            visible=FALSE,
                            clearWith=list(
                                "es",
                                "power",
                                "sample",
                                "alpha",
                                "aim",
                                "tails",
                                "df_model",
                                "r2",
                                "power_r2"),
                            columns=list(
                                list(
                                    `name`="es", 
                                    `title`="True effect size", 
                                    `type`="number"),
                                list(
                                    `name`="power", 
                                    `title`="Power to detect", 
                                    `type`="text"),
                                list(
                                    `name`="desc", 
                                    `title`="Description", 
                                    `type`="text"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)",
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "df_model",
                    "r2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !aim:n)",
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "df_model",
                    "r2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !aim:es)",
                clearWith=list(
                    "es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "df_model",
                    "r2")))}))

pamlglmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlglm",
                version = c(0,0,1),
                options = options,
                results = pamlglmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' GLM power analysis
#'
#' Something here
#' 
#' @param .caller .
#' @param aim .
#' @param es .
#' @param r2 .
#' @param df_model .
#' @param power_r2 .
#' @param power .
#' @param sample .
#' @param alpha .
#' @param tails .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerr2$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerr2$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlglm <- function(
    .caller = "glmbeta",
    aim = "n",
    es = 0.2,
    r2 = 0.04,
    df_model = 1,
    power_r2,
    power = 0.9,
    sample = 20,
    alpha = 0.05,
    tails = "two",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlglm requires jmvcore to be installed (restart may be required)")


    options <- pamlglmOptions$new(
        .caller = .caller,
        aim = aim,
        es = es,
        r2 = r2,
        df_model = df_model,
        power_r2 = power_r2,
        power = power,
        sample = sample,
        alpha = alpha,
        tails = tails,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve)

    analysis <- pamlglmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

