
# This file is automatically generated, you probably don't want to edit this

pamlglmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "glm",
            aim = "n",
            mode = "variance",
            b_es = 0.2,
            r2 = 0.04,
            b_df_model = 1,
            v_es = 0.2,
            v_df_model = 1,
            v_df_effect = 1,
            power = 0.9,
            sample = 20,
            alpha = 0.05,
            tails = "two",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE,
            covs = 1,
            factors = 0,
            factors_list = list(
                list(var="factor 1", levels=0)),
            covs_order = NULL,
            factors_order = NULL,
            mixed_order = NULL,
            eta = 0.2,
            eta_df = 0,
            eta_df_error = 0,
            epsilon = 0,
            omega = 0,
            use = "none", ...) {

            super$initialize(
                package="pamlj",
                name="pamlglm",
                requiresData=FALSE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="glm",
                hidden=TRUE)
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es",
                    "alpha"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "variance",
                    "beta"),
                default="variance")
            private$..b_es <- jmvcore::OptionNumber$new(
                "b_es",
                b_es,
                default=0.2)
            private$..r2 <- jmvcore::OptionNumber$new(
                "r2",
                r2,
                default=0.04)
            private$..b_df_model <- jmvcore::OptionNumber$new(
                "b_df_model",
                b_df_model,
                default=1)
            private$..v_es <- jmvcore::OptionNumber$new(
                "v_es",
                v_es,
                default=0.2)
            private$..v_df_model <- jmvcore::OptionNumber$new(
                "v_df_model",
                v_df_model,
                default=1)
            private$..v_df_effect <- jmvcore::OptionNumber$new(
                "v_df_effect",
                v_df_effect,
                default=1)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sample <- jmvcore::OptionNumber$new(
                "sample",
                sample,
                default=20)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..tails <- jmvcore::OptionList$new(
                "tails",
                tails,
                default="two",
                options=list(
                    "two",
                    "one"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..covs <- jmvcore::OptionNumber$new(
                "covs",
                covs,
                default=1,
                min=0)
            private$..factors <- jmvcore::OptionNumber$new(
                "factors",
                factors,
                default=0,
                min=0)
            private$..factors_list <- jmvcore::OptionArray$new(
                "factors_list",
                factors_list,
                default=list(
                    list(var="factor 1", levels=0)),
                template=jmvcore::OptionGroup$new(
                    "factors_list",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionInteger$new(
                            "levels",
                            NULL))))
            private$..covs_order <- jmvcore::OptionList$new(
                "covs_order",
                covs_order,
                options=list(
                    "main",
                    "order2",
                    "order3",
                    "orderall"))
            private$..factors_order <- jmvcore::OptionList$new(
                "factors_order",
                factors_order,
                options=list(
                    "main",
                    "order2",
                    "order3",
                    "orderall"))
            private$..mixed_order <- jmvcore::OptionList$new(
                "mixed_order",
                mixed_order,
                options=list(
                    "none",
                    "order2",
                    "order3",
                    "orderall"))
            private$..eta <- jmvcore::OptionNumber$new(
                "eta",
                eta,
                default=0.2)
            private$..eta_df <- jmvcore::OptionNumber$new(
                "eta_df",
                eta_df,
                default=0)
            private$..eta_df_error <- jmvcore::OptionNumber$new(
                "eta_df_error",
                eta_df_error,
                default=0)
            private$..epsilon <- jmvcore::OptionNumber$new(
                "epsilon",
                epsilon,
                default=0)
            private$..omega <- jmvcore::OptionNumber$new(
                "omega",
                omega,
                default=0)
            private$..use <- jmvcore::OptionList$new(
                "use",
                use,
                options=list(
                    "none",
                    "omega",
                    "epsilon"),
                default="none")

            self$.addOption(private$...caller)
            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..b_es)
            self$.addOption(private$..r2)
            self$.addOption(private$..b_df_model)
            self$.addOption(private$..v_es)
            self$.addOption(private$..v_df_model)
            self$.addOption(private$..v_df_effect)
            self$.addOption(private$..power)
            self$.addOption(private$..sample)
            self$.addOption(private$..alpha)
            self$.addOption(private$..tails)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..factors_list)
            self$.addOption(private$..covs_order)
            self$.addOption(private$..factors_order)
            self$.addOption(private$..mixed_order)
            self$.addOption(private$..eta)
            self$.addOption(private$..eta_df)
            self$.addOption(private$..eta_df_error)
            self$.addOption(private$..epsilon)
            self$.addOption(private$..omega)
            self$.addOption(private$..use)
        }),
    active = list(
        .caller = function() private$...caller$value,
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        b_es = function() private$..b_es$value,
        r2 = function() private$..r2$value,
        b_df_model = function() private$..b_df_model$value,
        v_es = function() private$..v_es$value,
        v_df_model = function() private$..v_df_model$value,
        v_df_effect = function() private$..v_df_effect$value,
        power = function() private$..power$value,
        sample = function() private$..sample$value,
        alpha = function() private$..alpha$value,
        tails = function() private$..tails$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        factors_list = function() private$..factors_list$value,
        covs_order = function() private$..covs_order$value,
        factors_order = function() private$..factors_order$value,
        mixed_order = function() private$..mixed_order$value,
        eta = function() private$..eta$value,
        eta_df = function() private$..eta_df$value,
        eta_df_error = function() private$..eta_df_error$value,
        epsilon = function() private$..epsilon$value,
        omega = function() private$..omega$value,
        use = function() private$..use$value),
    private = list(
        ...caller = NA,
        ..aim = NA,
        ..mode = NA,
        ..b_es = NA,
        ..r2 = NA,
        ..b_df_model = NA,
        ..v_es = NA,
        ..v_df_model = NA,
        ..v_df_effect = NA,
        ..power = NA,
        ..sample = NA,
        ..alpha = NA,
        ..tails = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA,
        ..covs = NA,
        ..factors = NA,
        ..factors_list = NA,
        ..covs_order = NA,
        ..factors_order = NA,
        ..mixed_order = NA,
        ..eta = NA,
        ..eta_df = NA,
        ..eta_df_error = NA,
        ..epsilon = NA,
        ..omega = NA,
        ..use = NA)
)

pamlglmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GLM power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="aes", 
                        `title`="f\u00B2", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="df(res)", 
                        `type`="integer"),
                    list(
                        `name`="alpha", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2"),
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !aim:n)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !aim:es)",
                clearWith=list(
                    "mode",
                    "b_es",
                    "v_es",
                    "power",
                    "sample",
                    "alpha",
                    "aim",
                    "tails",
                    "b_df_model",
                    "v_df_model",
                    "r2")))}))

pamlglmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlglmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlglm",
                version = c(0,0,1),
                options = options,
                results = pamlglmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' GLM power analysis
#'
#' Something here
#' 
#' @param .caller .
#' @param aim .
#' @param mode .
#' @param b_es .
#' @param r2 .
#' @param b_df_model .
#' @param v_es .
#' @param v_df_model .
#' @param v_df_effect .
#' @param power .
#' @param sample .
#' @param alpha .
#' @param tails .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @param covs .
#' @param factors .
#' @param factors_list .
#' @param covs_order .
#' @param factors_order .
#' @param mixed_order .
#' @param eta .
#' @param eta_df .
#' @param eta_df_error .
#' @param epsilon .
#' @param omega .
#' @param use .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlglm <- function(
    .caller = "glm",
    aim = "n",
    mode = "variance",
    b_es = 0.2,
    r2 = 0.04,
    b_df_model = 1,
    v_es = 0.2,
    v_df_model = 1,
    v_df_effect = 1,
    power = 0.9,
    sample = 20,
    alpha = 0.05,
    tails = "two",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE,
    covs = 1,
    factors = 0,
    factors_list = list(
                list(var="factor 1", levels=0)),
    covs_order,
    factors_order,
    mixed_order,
    eta = 0.2,
    eta_df = 0,
    eta_df_error = 0,
    epsilon = 0,
    omega = 0,
    use = "none") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlglm requires jmvcore to be installed (restart may be required)")


    options <- pamlglmOptions$new(
        .caller = .caller,
        aim = aim,
        mode = mode,
        b_es = b_es,
        r2 = r2,
        b_df_model = b_df_model,
        v_es = v_es,
        v_df_model = v_df_model,
        v_df_effect = v_df_effect,
        power = power,
        sample = sample,
        alpha = alpha,
        tails = tails,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve,
        covs = covs,
        factors = factors,
        factors_list = factors_list,
        covs_order = covs_order,
        factors_order = factors_order,
        mixed_order = mixed_order,
        eta = eta,
        eta_df = eta_df,
        eta_df_error = eta_df_error,
        epsilon = epsilon,
        omega = omega,
        use = use)

    analysis <- pamlglmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

