
# This file is automatically generated, you probably don't want to edit this

pamlttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "ttest",
            aim = "n",
            mode = "ttestind",
            ttestind_es = 0.5,
            ttestind_n = 20,
            ttestind_nratio = 1,
            ttestpaired_es = 0.5,
            ttestpaired_n = 20,
            ttestone_es = 0.5,
            ttestone_n = 20,
            is_equi = FALSE,
            equi_limit = 0.1,
            power = 0.9,
            sig.level = 0.05,
            alternative = "two.sided",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE,
            plot_log = FALSE,
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 0,
            plot_z_value = list(),
            plot_to_table = FALSE, ...) {

            super$initialize(
                package="pamlj",
                name="pamlttest",
                requiresData=FALSE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="ttest",
                hidden=TRUE)
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "ttestind",
                    "ttestpaired",
                    "ttestone"),
                default="ttestind")
            private$..ttestind_es <- jmvcore::OptionNumber$new(
                "ttestind_es",
                ttestind_es,
                default=0.5)
            private$..ttestind_n <- jmvcore::OptionNumber$new(
                "ttestind_n",
                ttestind_n,
                default=20)
            private$..ttestind_nratio <- jmvcore::OptionNumber$new(
                "ttestind_nratio",
                ttestind_nratio,
                default=1)
            private$..ttestpaired_es <- jmvcore::OptionNumber$new(
                "ttestpaired_es",
                ttestpaired_es,
                default=0.5)
            private$..ttestpaired_n <- jmvcore::OptionNumber$new(
                "ttestpaired_n",
                ttestpaired_n,
                default=20)
            private$..ttestone_es <- jmvcore::OptionNumber$new(
                "ttestone_es",
                ttestone_es,
                default=0.5)
            private$..ttestone_n <- jmvcore::OptionNumber$new(
                "ttestone_n",
                ttestone_n,
                default=20)
            private$..is_equi <- jmvcore::OptionBool$new(
                "is_equi",
                is_equi,
                default=FALSE)
            private$..equi_limit <- jmvcore::OptionNumber$new(
                "equi_limit",
                equi_limit,
                default=0.1)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                default="two.sided",
                options=list(
                    "two.sided",
                    "greater"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=FALSE)
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=0)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..plot_to_table <- jmvcore::OptionBool$new(
                "plot_to_table",
                plot_to_table,
                default=FALSE)

            self$.addOption(private$...caller)
            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..ttestind_es)
            self$.addOption(private$..ttestind_n)
            self$.addOption(private$..ttestind_nratio)
            self$.addOption(private$..ttestpaired_es)
            self$.addOption(private$..ttestpaired_n)
            self$.addOption(private$..ttestone_es)
            self$.addOption(private$..ttestone_n)
            self$.addOption(private$..is_equi)
            self$.addOption(private$..equi_limit)
            self$.addOption(private$..power)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..alternative)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..plot_to_table)
        }),
    active = list(
        .caller = function() private$...caller$value,
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        ttestind_es = function() private$..ttestind_es$value,
        ttestind_n = function() private$..ttestind_n$value,
        ttestind_nratio = function() private$..ttestind_nratio$value,
        ttestpaired_es = function() private$..ttestpaired_es$value,
        ttestpaired_n = function() private$..ttestpaired_n$value,
        ttestone_es = function() private$..ttestone_es$value,
        ttestone_n = function() private$..ttestone_n$value,
        is_equi = function() private$..is_equi$value,
        equi_limit = function() private$..equi_limit$value,
        power = function() private$..power$value,
        sig.level = function() private$..sig.level$value,
        alternative = function() private$..alternative$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        plot_to_table = function() private$..plot_to_table$value),
    private = list(
        ...caller = NA,
        ..aim = NA,
        ..mode = NA,
        ..ttestind_es = NA,
        ..ttestind_n = NA,
        ..ttestind_nratio = NA,
        ..ttestpaired_es = NA,
        ..ttestpaired_n = NA,
        ..ttestone_es = NA,
        ..ttestone_n = NA,
        ..is_equi = NA,
        ..equi_limit = NA,
        ..power = NA,
        ..sig.level = NA,
        ..alternative = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..plot_to_table = NA)
)

pamlttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlttestResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        issues = function() private$.items[["issues"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        plotnotes = function() private$.items[["plotnotes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        customnotes = function() private$.items[["customnotes"]],
        powerCustom = function() private$.items[["powerCustom"]],
        customtable = function() private$.items[["customtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="T-Test power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                refs="pwr",
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="n1", 
                        `title`="N\u2081", 
                        `type`="integer", 
                        `visible`=FALSE),
                    list(
                        `name`="n2", 
                        `title`="N\u2082", 
                        `type`="integer", 
                        `visible`=FALSE),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="sig.level", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour & !is_equi)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !is_equi)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !is_equi)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="customnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="customtable",
                title="Power Analysis parameters",
                visible="(plot_to_table && !plot_x:none && !plot_y:none)",
                columns=list(
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number", 
                        `visible`=FALSE),
                    list(
                        `name`="n1", 
                        `title`="N\u2081", 
                        `type`="integer", 
                        `visible`=FALSE),
                    list(
                        `name`="n2", 
                        `title`="N\u2082", 
                        `type`="integer", 
                        `visible`=FALSE))))}))

pamlttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlttest",
                version = c(0,2,0),
                options = options,
                results = pamlttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' T-Test
#'
#' Something here
#' 
#' @param .caller .
#' @param aim .
#' @param mode .
#' @param ttestind_es .
#' @param ttestind_n .
#' @param ttestind_nratio .
#' @param ttestpaired_es .
#' @param ttestpaired_n .
#' @param ttestone_es .
#' @param ttestone_n .
#' @param is_equi .
#' @param equi_limit .
#' @param power .
#' @param sig.level .
#' @param alternative .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @param plot_log .
#' @param plot_x .
#' @param plot_y .
#' @param plot_custom_labels .
#' @param plot_z .
#' @param plot_x_from .
#' @param plot_x_to .
#' @param plot_z_lines .
#' @param plot_z_value .
#' @param plot_to_table .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$customnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$customtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlttest <- function(
    .caller = "ttest",
    aim = "n",
    mode = "ttestind",
    ttestind_es = 0.5,
    ttestind_n = 20,
    ttestind_nratio = 1,
    ttestpaired_es = 0.5,
    ttestpaired_n = 20,
    ttestone_es = 0.5,
    ttestone_n = 20,
    is_equi = FALSE,
    equi_limit = 0.1,
    power = 0.9,
    sig.level = 0.05,
    alternative = "two.sided",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE,
    plot_log = FALSE,
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 0,
    plot_z_value = list(),
    plot_to_table = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlttest requires jmvcore to be installed (restart may be required)")


    options <- pamlttestOptions$new(
        .caller = .caller,
        aim = aim,
        mode = mode,
        ttestind_es = ttestind_es,
        ttestind_n = ttestind_n,
        ttestind_nratio = ttestind_nratio,
        ttestpaired_es = ttestpaired_es,
        ttestpaired_n = ttestpaired_n,
        ttestone_es = ttestone_es,
        ttestone_n = ttestone_n,
        is_equi = is_equi,
        equi_limit = equi_limit,
        power = power,
        sig.level = sig.level,
        alternative = alternative,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        plot_to_table = plot_to_table)

    analysis <- pamlttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

