
# This file is automatically generated, you probably don't want to edit this

pamlpropOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlpropOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "proportions",
            aim = "n",
            mode = "propind",
            propind_p1 = 0.6,
            propind_p2 = 0.5,
            propind_n = 20,
            propind_nratio = 1,
            propone_p1 = 0.6,
            propone_p2 = 0.5,
            propone_n = 20,
            proppaired_p1 = 0.4,
            proppaired_p2 = 0.2,
            proppaired_n = 20,
            power = 0.9,
            sig.level = 0.05,
            alternative = "two.sided",
            plot_contour = FALSE,
            plot_escurve = FALSE,
            plot_ncurve = FALSE,
            plot_log = TRUE,
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 0,
            plot_z_value = list(),
            es_type = "odd", ...) {

            super$initialize(
                package="pamlj",
                name="pamlprop",
                requiresData=FALSE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="proportions",
                hidden=TRUE)
            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "propind",
                    "propone",
                    "proppaired"),
                default="propind")
            private$..propind_p1 <- jmvcore::OptionNumber$new(
                "propind_p1",
                propind_p1,
                default=0.6)
            private$..propind_p2 <- jmvcore::OptionNumber$new(
                "propind_p2",
                propind_p2,
                default=0.5)
            private$..propind_n <- jmvcore::OptionNumber$new(
                "propind_n",
                propind_n,
                default=20)
            private$..propind_nratio <- jmvcore::OptionNumber$new(
                "propind_nratio",
                propind_nratio,
                default=1)
            private$..propone_p1 <- jmvcore::OptionNumber$new(
                "propone_p1",
                propone_p1,
                default=0.6)
            private$..propone_p2 <- jmvcore::OptionNumber$new(
                "propone_p2",
                propone_p2,
                default=0.5)
            private$..propone_n <- jmvcore::OptionNumber$new(
                "propone_n",
                propone_n,
                default=20)
            private$..proppaired_p1 <- jmvcore::OptionNumber$new(
                "proppaired_p1",
                proppaired_p1,
                default=0.4)
            private$..proppaired_p2 <- jmvcore::OptionNumber$new(
                "proppaired_p2",
                proppaired_p2,
                default=0.2)
            private$..proppaired_n <- jmvcore::OptionNumber$new(
                "proppaired_n",
                proppaired_n,
                default=20)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                default="two.sided",
                options=list(
                    "two.sided",
                    "greater"))
            private$..plot_contour <- jmvcore::OptionBool$new(
                "plot_contour",
                plot_contour,
                default=FALSE)
            private$..plot_escurve <- jmvcore::OptionBool$new(
                "plot_escurve",
                plot_escurve,
                default=FALSE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=TRUE)
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power",
                    "es",
                    "sig.level"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=0)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..es_type <- jmvcore::OptionList$new(
                "es_type",
                es_type,
                default="odd",
                options=list(
                    "odd",
                    "dif",
                    "rr"))

            self$.addOption(private$...caller)
            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..propind_p1)
            self$.addOption(private$..propind_p2)
            self$.addOption(private$..propind_n)
            self$.addOption(private$..propind_nratio)
            self$.addOption(private$..propone_p1)
            self$.addOption(private$..propone_p2)
            self$.addOption(private$..propone_n)
            self$.addOption(private$..proppaired_p1)
            self$.addOption(private$..proppaired_p2)
            self$.addOption(private$..proppaired_n)
            self$.addOption(private$..power)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..alternative)
            self$.addOption(private$..plot_contour)
            self$.addOption(private$..plot_escurve)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..es_type)
        }),
    active = list(
        .caller = function() private$...caller$value,
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        propind_p1 = function() private$..propind_p1$value,
        propind_p2 = function() private$..propind_p2$value,
        propind_n = function() private$..propind_n$value,
        propind_nratio = function() private$..propind_nratio$value,
        propone_p1 = function() private$..propone_p1$value,
        propone_p2 = function() private$..propone_p2$value,
        propone_n = function() private$..propone_n$value,
        proppaired_p1 = function() private$..proppaired_p1$value,
        proppaired_p2 = function() private$..proppaired_p2$value,
        proppaired_n = function() private$..proppaired_n$value,
        power = function() private$..power$value,
        sig.level = function() private$..sig.level$value,
        alternative = function() private$..alternative$value,
        plot_contour = function() private$..plot_contour$value,
        plot_escurve = function() private$..plot_escurve$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        es_type = function() private$..es_type$value),
    private = list(
        ...caller = NA,
        ..aim = NA,
        ..mode = NA,
        ..propind_p1 = NA,
        ..propind_p2 = NA,
        ..propind_n = NA,
        ..propind_nratio = NA,
        ..propone_p1 = NA,
        ..propone_p2 = NA,
        ..propone_n = NA,
        ..proppaired_p1 = NA,
        ..proppaired_p2 = NA,
        ..proppaired_n = NA,
        ..power = NA,
        ..sig.level = NA,
        ..alternative = NA,
        ..plot_contour = NA,
        ..plot_escurve = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..es_type = NA)
)

pamlpropResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlpropResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        issues = function() private$.items[["issues"]],
        powertab = function() private$.items[["powertab"]],
        powerbyes = function() private$.items[["powerbyes"]],
        powerContour = function() private$.items[["powerContour"]],
        powerEscurve = function() private$.items[["powerEscurve"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        powerCustom = function() private$.items[["powerCustom"]],
        plotnotes = function() private$.items[["plotnotes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Proportions power analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                refs="pwr",
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="n1", 
                        `title`="N\u2081", 
                        `type`="integer"),
                    list(
                        `name`="n2", 
                        `title`="N\u2082", 
                        `type`="integer"),
                    list(
                        `name`="p1", 
                        `title`="P\u2081", 
                        `type`="number"),
                    list(
                        `name`="p2", 
                        `title`="P\u2082", 
                        `type`="number"),
                    list(
                        `name`="es", 
                        `title`="es", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="sig.level", 
                        `title`="&alpha;", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyes",
                title="Power by Effect Size",
                rows=4,
                columns=list(
                    list(
                        `name`="es", 
                        `title`="True effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerContour",
                title="Power Contour",
                width=400,
                height=350,
                renderFun=".plot_contour",
                visible="(plot_contour)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerEscurve",
                title="Power Curve by Effect Size",
                width=400,
                height=350,
                renderFun=".plot_escurve",
                visible="(plot_escurve & !aim:n)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve & !aim:es)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=TRUE))}))

pamlpropBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlpropBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlprop",
                version = c(0,0,1),
                options = options,
                results = pamlpropResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Propotions
#'
#' Something here
#' 
#' @param .caller .
#' @param aim .
#' @param mode .
#' @param propind_p1 .
#' @param propind_p2 .
#' @param propind_n .
#' @param propind_nratio .
#' @param propone_p1 .
#' @param propone_p2 .
#' @param propone_n .
#' @param proppaired_p1 .
#' @param proppaired_p2 .
#' @param proppaired_n .
#' @param power .
#' @param sig.level .
#' @param alternative .
#' @param plot_contour .
#' @param plot_escurve .
#' @param plot_ncurve .
#' @param plot_log .
#' @param plot_x .
#' @param plot_y .
#' @param plot_custom_labels .
#' @param plot_z .
#' @param plot_x_from .
#' @param plot_x_to .
#' @param plot_z_lines .
#' @param plot_z_value .
#' @param es_type .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerContour} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerEscurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlprop <- function(
    .caller = "proportions",
    aim = "n",
    mode = "propind",
    propind_p1 = 0.6,
    propind_p2 = 0.5,
    propind_n = 20,
    propind_nratio = 1,
    propone_p1 = 0.6,
    propone_p2 = 0.5,
    propone_n = 20,
    proppaired_p1 = 0.4,
    proppaired_p2 = 0.2,
    proppaired_n = 20,
    power = 0.9,
    sig.level = 0.05,
    alternative = "two.sided",
    plot_contour = FALSE,
    plot_escurve = FALSE,
    plot_ncurve = FALSE,
    plot_log = TRUE,
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 0,
    plot_z_value = list(),
    es_type = "odd") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlprop requires jmvcore to be installed (restart may be required)")


    options <- pamlpropOptions$new(
        .caller = .caller,
        aim = aim,
        mode = mode,
        propind_p1 = propind_p1,
        propind_p2 = propind_p2,
        propind_n = propind_n,
        propind_nratio = propind_nratio,
        propone_p1 = propone_p1,
        propone_p2 = propone_p2,
        propone_n = propone_n,
        proppaired_p1 = proppaired_p1,
        proppaired_p2 = proppaired_p2,
        proppaired_n = proppaired_n,
        power = power,
        sig.level = sig.level,
        alternative = alternative,
        plot_contour = plot_contour,
        plot_escurve = plot_escurve,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        es_type = es_type)

    analysis <- pamlpropClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

