
# This file is automatically generated, you probably don't want to edit this

pamlmedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aim = "n",
            mode = "medsimple",
            a = 0.3,
            b = 0.3,
            cprime = 0,
            model_type = "twomeds",
            a1 = "",
            b1 = "",
            a2 = "",
            b2 = "",
            a3 = "",
            b3 = "",
            d1 = "",
            d2 = "",
            r12 = "",
            r13 = "",
            r23 = "",
            cprime2 = 0,
            power = 0.9,
            n = 100,
            sig.level = 0.05,
            alternative = "two.sided",
            test = "joint",
            mcR = 1000,
            parallel = FALSE,
            table_pwbyn = TRUE,
            plot_ncurve = FALSE,
            plot_log = FALSE,
            plot_x = "none",
            plot_y = "none",
            plot_custom_labels = FALSE,
            plot_z = "none",
            plot_x_from = 0,
            plot_x_to = 0,
            plot_z_lines = 1,
            plot_z_value = list(),
            plot_to_table = FALSE,
            test_c = FALSE,
            explain = FALSE,
            diagram = TRUE,
            .interface = "jamovi",
            .caller = "mediation", ...) {

            super$initialize(
                package="pamlj",
                name="pamlmed",
                requiresData=FALSE,
                ...)

            private$..aim <- jmvcore::OptionList$new(
                "aim",
                aim,
                default="n",
                options=list(
                    "n",
                    "power",
                    "es"))
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "medsimple",
                    "medcomplex"),
                default="medsimple")
            private$..a <- jmvcore::OptionNumber$new(
                "a",
                a,
                default=0.3)
            private$..b <- jmvcore::OptionNumber$new(
                "b",
                b,
                default=0.3)
            private$..cprime <- jmvcore::OptionNumber$new(
                "cprime",
                cprime,
                default=0)
            private$..model_type <- jmvcore::OptionList$new(
                "model_type",
                model_type,
                options=list(
                    "twomeds",
                    "threemeds",
                    "twoserial"),
                default="twomeds")
            private$..a1 <- jmvcore::OptionString$new(
                "a1",
                a1,
                default="")
            private$..b1 <- jmvcore::OptionString$new(
                "b1",
                b1,
                default="")
            private$..a2 <- jmvcore::OptionString$new(
                "a2",
                a2,
                default="")
            private$..b2 <- jmvcore::OptionString$new(
                "b2",
                b2,
                default="")
            private$..a3 <- jmvcore::OptionString$new(
                "a3",
                a3,
                default="")
            private$..b3 <- jmvcore::OptionString$new(
                "b3",
                b3,
                default="")
            private$..d1 <- jmvcore::OptionString$new(
                "d1",
                d1,
                default="")
            private$..d2 <- jmvcore::OptionString$new(
                "d2",
                d2,
                default="")
            private$..r12 <- jmvcore::OptionString$new(
                "r12",
                r12,
                default="")
            private$..r13 <- jmvcore::OptionString$new(
                "r13",
                r13,
                default="")
            private$..r23 <- jmvcore::OptionString$new(
                "r23",
                r23,
                default="")
            private$..cprime2 <- jmvcore::OptionNumber$new(
                "cprime2",
                cprime2,
                default=0)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.9)
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=100)
            private$..sig.level <- jmvcore::OptionNumber$new(
                "sig.level",
                sig.level,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                default="two.sided",
                options=list(
                    "two.sided",
                    "one.sided"))
            private$..test <- jmvcore::OptionList$new(
                "test",
                test,
                default="joint",
                options=list(
                    "joint",
                    "sobel",
                    "mc"))
            private$..mcR <- jmvcore::OptionNumber$new(
                "mcR",
                mcR,
                default=1000)
            private$..parallel <- jmvcore::OptionBool$new(
                "parallel",
                parallel,
                default=FALSE)
            private$..table_pwbyn <- jmvcore::OptionBool$new(
                "table_pwbyn",
                table_pwbyn,
                default=TRUE)
            private$..plot_ncurve <- jmvcore::OptionBool$new(
                "plot_ncurve",
                plot_ncurve,
                default=FALSE)
            private$..plot_log <- jmvcore::OptionBool$new(
                "plot_log",
                plot_log,
                default=FALSE)
            private$..plot_x <- jmvcore::OptionList$new(
                "plot_x",
                plot_x,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power"))
            private$..plot_y <- jmvcore::OptionList$new(
                "plot_y",
                plot_y,
                default="none",
                options=list(
                    "none",
                    "n",
                    "power"))
            private$..plot_custom_labels <- jmvcore::OptionBool$new(
                "plot_custom_labels",
                plot_custom_labels,
                default=FALSE)
            private$..plot_z <- jmvcore::OptionList$new(
                "plot_z",
                plot_z,
                default="none",
                options=list(
                    "none",
                    "sig.level"))
            private$..plot_x_from <- jmvcore::OptionNumber$new(
                "plot_x_from",
                plot_x_from,
                default=0)
            private$..plot_x_to <- jmvcore::OptionNumber$new(
                "plot_x_to",
                plot_x_to,
                default=0)
            private$..plot_z_lines <- jmvcore::OptionNumber$new(
                "plot_z_lines",
                plot_z_lines,
                default=1,
                min=1)
            private$..plot_z_value <- jmvcore::OptionArray$new(
                "plot_z_value",
                plot_z_value,
                default=list(),
                template=jmvcore::OptionString$new(
                    "plot_z_value",
                    NULL))
            private$..plot_to_table <- jmvcore::OptionBool$new(
                "plot_to_table",
                plot_to_table,
                default=FALSE)
            private$..test_c <- jmvcore::OptionBool$new(
                "test_c",
                test_c,
                default=FALSE)
            private$..explain <- jmvcore::OptionBool$new(
                "explain",
                explain,
                default=FALSE)
            private$..diagram <- jmvcore::OptionBool$new(
                "diagram",
                diagram,
                default=TRUE)
            private$...interface <- jmvcore::OptionString$new(
                ".interface",
                .interface,
                default="jamovi",
                hidden=TRUE)
            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="mediation",
                hidden=TRUE)

            self$.addOption(private$..aim)
            self$.addOption(private$..mode)
            self$.addOption(private$..a)
            self$.addOption(private$..b)
            self$.addOption(private$..cprime)
            self$.addOption(private$..model_type)
            self$.addOption(private$..a1)
            self$.addOption(private$..b1)
            self$.addOption(private$..a2)
            self$.addOption(private$..b2)
            self$.addOption(private$..a3)
            self$.addOption(private$..b3)
            self$.addOption(private$..d1)
            self$.addOption(private$..d2)
            self$.addOption(private$..r12)
            self$.addOption(private$..r13)
            self$.addOption(private$..r23)
            self$.addOption(private$..cprime2)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..sig.level)
            self$.addOption(private$..alternative)
            self$.addOption(private$..test)
            self$.addOption(private$..mcR)
            self$.addOption(private$..parallel)
            self$.addOption(private$..table_pwbyn)
            self$.addOption(private$..plot_ncurve)
            self$.addOption(private$..plot_log)
            self$.addOption(private$..plot_x)
            self$.addOption(private$..plot_y)
            self$.addOption(private$..plot_custom_labels)
            self$.addOption(private$..plot_z)
            self$.addOption(private$..plot_x_from)
            self$.addOption(private$..plot_x_to)
            self$.addOption(private$..plot_z_lines)
            self$.addOption(private$..plot_z_value)
            self$.addOption(private$..plot_to_table)
            self$.addOption(private$..test_c)
            self$.addOption(private$..explain)
            self$.addOption(private$..diagram)
            self$.addOption(private$...interface)
            self$.addOption(private$...caller)
        }),
    active = list(
        aim = function() private$..aim$value,
        mode = function() private$..mode$value,
        a = function() private$..a$value,
        b = function() private$..b$value,
        cprime = function() private$..cprime$value,
        model_type = function() private$..model_type$value,
        a1 = function() private$..a1$value,
        b1 = function() private$..b1$value,
        a2 = function() private$..a2$value,
        b2 = function() private$..b2$value,
        a3 = function() private$..a3$value,
        b3 = function() private$..b3$value,
        d1 = function() private$..d1$value,
        d2 = function() private$..d2$value,
        r12 = function() private$..r12$value,
        r13 = function() private$..r13$value,
        r23 = function() private$..r23$value,
        cprime2 = function() private$..cprime2$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        sig.level = function() private$..sig.level$value,
        alternative = function() private$..alternative$value,
        test = function() private$..test$value,
        mcR = function() private$..mcR$value,
        parallel = function() private$..parallel$value,
        table_pwbyn = function() private$..table_pwbyn$value,
        plot_ncurve = function() private$..plot_ncurve$value,
        plot_log = function() private$..plot_log$value,
        plot_x = function() private$..plot_x$value,
        plot_y = function() private$..plot_y$value,
        plot_custom_labels = function() private$..plot_custom_labels$value,
        plot_z = function() private$..plot_z$value,
        plot_x_from = function() private$..plot_x_from$value,
        plot_x_to = function() private$..plot_x_to$value,
        plot_z_lines = function() private$..plot_z_lines$value,
        plot_z_value = function() private$..plot_z_value$value,
        plot_to_table = function() private$..plot_to_table$value,
        test_c = function() private$..test_c$value,
        explain = function() private$..explain$value,
        diagram = function() private$..diagram$value,
        .interface = function() private$...interface$value,
        .caller = function() private$...caller$value),
    private = list(
        ..aim = NA,
        ..mode = NA,
        ..a = NA,
        ..b = NA,
        ..cprime = NA,
        ..model_type = NA,
        ..a1 = NA,
        ..b1 = NA,
        ..a2 = NA,
        ..b2 = NA,
        ..a3 = NA,
        ..b3 = NA,
        ..d1 = NA,
        ..d2 = NA,
        ..r12 = NA,
        ..r13 = NA,
        ..r23 = NA,
        ..cprime2 = NA,
        ..power = NA,
        ..n = NA,
        ..sig.level = NA,
        ..alternative = NA,
        ..test = NA,
        ..mcR = NA,
        ..parallel = NA,
        ..table_pwbyn = NA,
        ..plot_ncurve = NA,
        ..plot_log = NA,
        ..plot_x = NA,
        ..plot_y = NA,
        ..plot_custom_labels = NA,
        ..plot_z = NA,
        ..plot_x_from = NA,
        ..plot_x_to = NA,
        ..plot_z_lines = NA,
        ..plot_z_value = NA,
        ..plot_to_table = NA,
        ..test_c = NA,
        ..explain = NA,
        ..diagram = NA,
        ...interface = NA,
        ...caller = NA)
)

pamlmedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmedResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        extrainfo = function() private$.items[["extrainfo"]],
        issues = function() private$.items[["issues"]],
        diagram = function() private$.items[["diagram"]],
        powertab = function() private$.items[["powertab"]],
        effectsize = function() private$.items[["effectsize"]],
        powerbyn = function() private$.items[["powerbyn"]],
        powerxy = function() private$.items[["powerxy"]],
        plotnotes = function() private$.items[["plotnotes"]],
        powerNcurve = function() private$.items[["powerNcurve"]],
        powerCustom = function() private$.items[["powerCustom"]],
        customnotes = function() private$.items[["customnotes"]],
        customtable = function() private$.items[["customtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mediation")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="extrainfo",
                title="Extra Info",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="issues",
                title="Issues",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="diagram",
                title="",
                width=500,
                height=400,
                renderFun=".plot_diagram",
                visible="(diagram)",
                clearWith=list(
                    "a",
                    "b",
                    "c",
                    "a1",
                    "b1",
                    "a2",
                    "b2",
                    "a3",
                    "b3",
                    "r12",
                    "r13",
                    "r23",
                    "d1",
                    "aim",
                    "mode",
                    "cprime",
                    "cprime2",
                    "model_type",
                    "mcR",
                    "parallel")))
            self$add(jmvcore::Table$new(
                options=options,
                name="powertab",
                title="A Priori Power Analysis",
                rows=1,
                refs=list(
                    "pamlj"),
                clearWith=list(
                    "a",
                    "b",
                    "c",
                    "a1",
                    "b1",
                    "a2",
                    "b2",
                    "a3",
                    "b3",
                    "r12",
                    "r13",
                    "r23",
                    "d1",
                    "aim",
                    "mode",
                    "cprime",
                    "cprime2",
                    "model_type",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "test",
                    "mcR",
                    "parallel"),
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="Effect", 
                        `type`="text", 
                        `visible`="(mode:medcomplex)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="a", 
                        `title`="X->M (a)", 
                        `type`="number"),
                    list(
                        `name`="b", 
                        `title`="M->Y (b)", 
                        `type`="number"),
                    list(
                        `name`="cprime", 
                        `title`="X->Y (c)", 
                        `type`="number"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="number"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="sig.level", 
                        `title`="\u03B1", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectsize",
                title="Computed Parameters",
                clearWith=list(
                    "a",
                    "b",
                    "c",
                    "a1",
                    "b1",
                    "a2",
                    "b2",
                    "a3",
                    "b3",
                    "r12",
                    "r13",
                    "r22",
                    "d1",
                    "aim",
                    "mode",
                    "cprime",
                    "cprime2",
                    "model_type",
                    "aim",
                    "mode",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "test",
                    "mcR",
                    "parallel"),
                columns=list(
                    list(
                        `name`="index", 
                        `title`="Index", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerbyn",
                title="Power by Sample size",
                rows=4,
                visible="(table_pwbyn)",
                clearWith=list(
                    "a",
                    "b",
                    "c",
                    "a1",
                    "b1",
                    "a2",
                    "b2",
                    "a3",
                    "b3",
                    "r12",
                    "r13",
                    "r23",
                    "d1",
                    "aim",
                    "mode",
                    "cprime",
                    "cprime2",
                    "model_type",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative",
                    "test"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="Sample size", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Power to detect", 
                        `type`="text"),
                    list(
                        `name`="desc", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerxy",
                title="Power Analysis for X Y effect without mediators (c)",
                rows=1,
                visible="(test_c)",
                refs=list(
                    "pamlj"),
                clearWith=list(
                    "a",
                    "b",
                    "c",
                    "a1",
                    "b1",
                    "a2",
                    "b2",
                    "a3",
                    "b3",
                    "r12",
                    "r13",
                    "r23",
                    "d1",
                    "aim",
                    "mode",
                    "cprime",
                    "cprime2",
                    "power",
                    "n",
                    "sig.level",
                    "aim",
                    "alternative"),
                columns=list(
                    list(
                        `name`="beta", 
                        `title`="\u03B2", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="number"),
                    list(
                        `name`="sig.level", 
                        `title`="\u03B1", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerNcurve",
                title="Power Curve by N",
                width=400,
                height=350,
                renderFun=".plot_ncurve",
                visible="(plot_ncurve)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCustom",
                title="Power Parameters",
                width=450,
                height=350,
                renderFun=".plot_custom",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="customnotes",
                title="Plot notes",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="customtable",
                title="Power Analysis parameters",
                visible="(plot_to_table && !plot_x:none && !plot_y:none)",
                columns=list(
                    list(
                        `name`="y", 
                        `title`="Y", 
                        `type`="number"),
                    list(
                        `name`="x", 
                        `title`="X", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number", 
                        `visible`=FALSE),
                    list(
                        `name`="es", 
                        `title`="ME", 
                        `type`="Number"))))}))

pamlmedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pamlmedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pamlj",
                name = "pamlmed",
                version = c(0,4,0),
                options = options,
                results = pamlmedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Mediation
#'
#' Something here
#' 
#' @param aim The aim of the analysis: \code{n} (default) for sample size,
#'   \code{power} to estimate power, \code{es} for effect size (correlation)
#' @param mode .
#' @param a The expected standardized effect of the independent variable on
#'   the mediator
#' @param b The expected standardized effect of the independent variable on
#'   the mediator
#' @param cprime The expected standardized effect of the independent variable
#'   on the mediator
#' @param model_type .
#' @param a1 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param b1 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param a2 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param b2 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param a3 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param b3 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param d1 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param d2 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param r12 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param r13 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param r23 The expected standardized effect of the independent variable on
#'   mediator 1
#' @param cprime2 The expected standardized effect of the independent variable
#'   on the mediator
#' @param power Minimal desired power
#' @param n Sample size
#' @param sig.level Type I error rate (significance cut-off or alpha)
#' @param alternative .
#' @param test .
#' @param mcR .
#' @param parallel .
#' @param table_pwbyn .
#' @param plot_ncurve .
#' @param plot_log .
#' @param plot_x .
#' @param plot_y .
#' @param plot_custom_labels .
#' @param plot_z .
#' @param plot_x_from .
#' @param plot_x_to .
#' @param plot_z_lines .
#' @param plot_z_value .
#' @param plot_to_table .
#' @param test_c .
#' @param explain .
#' @param diagram .
#' @param .interface Used for internal purposes
#' @param .caller Used for internal purposes
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$extrainfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$issues} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$diagram} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powertab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effectsize} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerbyn} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerxy} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$powerNcurve} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$powerCustom} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$customnotes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$customtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$powertab$asDF}
#'
#' \code{as.data.frame(results$powertab)}
#'
#' @export
pamlmed <- function(
    aim = "n",
    mode = "medsimple",
    a = 0.3,
    b = 0.3,
    cprime = 0,
    model_type = "twomeds",
    a1 = "",
    b1 = "",
    a2 = "",
    b2 = "",
    a3 = "",
    b3 = "",
    d1 = "",
    d2 = "",
    r12 = "",
    r13 = "",
    r23 = "",
    cprime2 = 0,
    power = 0.9,
    n = 100,
    sig.level = 0.05,
    alternative = "two.sided",
    test = "joint",
    mcR = 1000,
    parallel = FALSE,
    table_pwbyn = TRUE,
    plot_ncurve = FALSE,
    plot_log = FALSE,
    plot_x = "none",
    plot_y = "none",
    plot_custom_labels = FALSE,
    plot_z = "none",
    plot_x_from = 0,
    plot_x_to = 0,
    plot_z_lines = 1,
    plot_z_value = list(),
    plot_to_table = FALSE,
    test_c = FALSE,
    explain = FALSE,
    diagram = TRUE,
    .interface = "jamovi",
    .caller = "mediation") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pamlmed requires jmvcore to be installed (restart may be required)")


    options <- pamlmedOptions$new(
        aim = aim,
        mode = mode,
        a = a,
        b = b,
        cprime = cprime,
        model_type = model_type,
        a1 = a1,
        b1 = b1,
        a2 = a2,
        b2 = b2,
        a3 = a3,
        b3 = b3,
        d1 = d1,
        d2 = d2,
        r12 = r12,
        r13 = r13,
        r23 = r23,
        cprime2 = cprime2,
        power = power,
        n = n,
        sig.level = sig.level,
        alternative = alternative,
        test = test,
        mcR = mcR,
        parallel = parallel,
        table_pwbyn = table_pwbyn,
        plot_ncurve = plot_ncurve,
        plot_log = plot_log,
        plot_x = plot_x,
        plot_y = plot_y,
        plot_custom_labels = plot_custom_labels,
        plot_z = plot_z,
        plot_x_from = plot_x_from,
        plot_x_to = plot_x_to,
        plot_z_lines = plot_z_lines,
        plot_z_value = plot_z_value,
        plot_to_table = plot_to_table,
        test_c = test_c,
        explain = explain,
        diagram = diagram,
        .interface = .interface,
        .caller = .caller)

    analysis <- pamlmedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

